# Generated by Django 5.1.7 on 2025-07-28 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('contact_id', models.CharField(max_length=255, unique=True)),
                ('changed_properties', models.JSONField(blank=True, default=dict, null=True)),
                ('properties', models.JSONField(blank=True, default=dict, null=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('status_code', models.SmallIntegerField(choices=[(0, 'New'), (1, 'In Progress'), (5, 'Completed'), (19, 'Canceled'), (400, 'Error')], default=0)),
                ('test', models.SmallIntegerField(default=0)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
                'constraints': [models.UniqueConstraint(fields=('email', 'contact_id'), name='unique_email_contact_privser')],
            },
        ),
        migrations.CreateModel(
            name='Custom_Fields',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('privser_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('main_field', models.BooleanField(default=False)),
                ('privser_name', models.CharField(max_length=512)),
                ('privser_fieldKey', models.CharField(blank=True, max_length=512, null=True)),
                ('privser_placeholder', models.CharField(blank=True, max_length=255, null=True)),
                ('privser_dataType', models.CharField(blank=True, max_length=255, null=True)),
                ('exchange_property_name', models.CharField(blank=True, max_length=255, null=True)),
                ('no_sync', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exchange_property', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exchange.contacts_prop')),
            ],
            options={
                'verbose_name': 'Custom field',
                'verbose_name_plural': 'Custom fields',
            },
        ),
        migrations.CreateModel(
            name='Contacts_Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('contacts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='privser.contacts')),
                ('contacts_parameters', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parameters_custom_fields', to='privser.custom_fields')),
            ],
            options={
                'verbose_name': 'Parameters',
                'verbose_name_plural': 'Parameters',
            },
        ),
        migrations.CreateModel(
            name='Request_From_Privser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request', models.JSONField(default=dict)),
                ('status_code', models.SmallIntegerField(choices=[(0, 'New'), (1, 'In Progress'), (5, 'Completed'), (6, 'Ignore'), (9, 'No Email in Exchange'), (19, 'Canceled'), (400, 'Error')], default=0)),
                ('errors', models.JSONField(blank=True, default=dict, null=True)),
                ('critical', models.JSONField(blank=True, default=dict, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('contacts', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='request_from_privser', to='company.employees')),
            ],
            options={
                'verbose_name': 'Request from Privser',
                'verbose_name_plural': 'Requests from Privser',
            },
        ),
        migrations.CreateModel(
            name='Request_To_Privser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_properties', models.JSONField(blank=True, default=dict, null=True)),
                ('response_privser', models.JSONField(blank=True, default=dict, null=True)),
                ('status_code', models.SmallIntegerField(choices=[(0, 'New'), (1, 'In Progress'), (5, 'Completed'), (19, 'Canceled'), (35, 'EMAIL ERRORS'), (400, 'Error'), (404, 'Critical')], default=0)),
                ('errors', models.JSONField(blank=True, default=dict, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_to_privser_entries', to='company.employees')),
            ],
            options={
                'verbose_name': 'Request',
                'verbose_name_plural': 'Requests',
            },
        ),
    ]
