# Generated by Django 6.0.1 on 2026-01-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='employee_record',
            field=models.FileField(blank=True, help_text='Uploaded or generated employee record PDF.', null=True, upload_to='contacts/employee_records/'),
        ),
    ]
