# Generated by Django 6.0.1 on 2026-01-28 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_date_contact_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='qr_code',
            field=models.ImageField(blank=True, help_text="Auto-generated QR code encoding this contact's ID.", null=True, upload_to='contacts/qr_codes/'),
        ),
    ]
