# Generated by Django 6.0.1 on 2026-01-29 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='check_in',
            field=models.DateTimeField(blank=True, help_text='Last check-in time (set by PWA QR scan).', null=True),
        ),
    ]
