# Generated by Django 6.0.1 on 2026-02-03 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/profile_pictures/'),
        ),
    ]
