# Generated by Django 6.0.1 on 2026-02-04 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contact_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='privser_contact_id',
            field=models.CharField(blank=True, db_index=True, help_text='GoHighLevel contact id (linked record)', max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        )
,
    ]
