# Generated by Django 6.0.1 on 2026-02-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_contact_privser_contact_id_contact_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254),
        ),
    ]
