# Generated by Django 6.0.1 on 2026-02-11 23:46

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_company_date_company_text'),
        ('contacts', '0008_alter_contact_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='privser_contact_id',
            field=models.CharField(blank=True, db_index=True, help_text='GoHighLevel contact id (linked record)', max_length=64, null=True),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('email'), condition=models.Q(models.Q(('email', ''), _negated=True), ('email__isnull', False)), name='uniq_contact_email_ci'),
        ),
    ]
