# Generated by Django 5.1.7 on 2025-07-28 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('exchange', '0001_initial'),
        ('privser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sync',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('status_code', models.SmallIntegerField(choices=[(0, 'Not processed'), (1, 'In Progress'), (5, 'Completed'), (6, 'Ignore'), (7, 'No Changes'), (9, 'No Email in Exchange'), (19, 'Canceled'), (400, 'Error')], default=0)),
                ('test', models.SmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_privser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_privser', to='privser.contacts')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sync_employees', to='company.employees')),
            ],
            options={
                'verbose_name': 'Sync',
                'verbose_name_plural': 'Sync',
            },
        ),
        migrations.CreateModel(
            name='Sync_Parameters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('privser_value', models.TextField(blank=True, null=True)),
                ('privser_datetime', models.DateTimeField(blank=True, null=True)),
                ('privser_apply', models.BooleanField(default=False)),
                ('exchange_value', models.TextField(blank=True, null=True)),
                ('exchange_datetime', models.DateTimeField(blank=True, null=True)),
                ('exchange_apply', models.BooleanField(default=False)),
                ('exchange_property_not_found', models.CharField(blank=True, max_length=255, null=True)),
                ('privser_property_not_found', models.CharField(blank=True, max_length=255, null=True)),
                ('override_value', models.TextField(blank=True, null=True)),
                ('body', models.JSONField(blank=True, default=dict, null=True)),
                ('removed', models.BooleanField(default=False)),
                ('privser_custom_fields', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_parameters', to='privser.custom_fields')),
                ('sync', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_parameters', to='synchronization.sync')),
            ],
            options={
                'verbose_name': 'Awaiting Review',
                'verbose_name_plural': 'Awaiting Review',
            },
        ),
        migrations.CreateModel(
            name='ChangesInParameter',
            fields=[
            ],
            options={
                'verbose_name': 'Approved Parameters',
                'verbose_name_plural': 'Approved Parameters',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('synchronization.sync_parameters',),
        ),
        migrations.CreateModel(
            name='Sync_Delivery_Logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('contacts_prop_name', models.CharField(blank=True, max_length=255, null=True)),
                ('privser_custom_fields_name', models.CharField(blank=True, max_length=512, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('target_system', models.CharField(choices=[('Privser', 'Privser'), ('Exchange', 'Exchange'), ('Local', 'Local'), ('N/A', 'N/A')], default='N/A', max_length=20)),
                ('body', models.JSONField(blank=True, default=dict, null=True)),
                ('removed', models.BooleanField(default=False)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('status_code', models.CharField(choices=[('New', 'New'), ('Not Processed', 'Not Processed'), ('Processing', 'Processing'), ('Sync Completed', 'Sync Completed'), ('Ignored', 'Ignored'), ('No Data Changes', 'No Data Changes'), ('No Data Links', 'No Data Links'), ('No Contact Link', 'No Contact Link'), ('Multiple Contact Link', 'Multiple Contact Link'), ('No Parameter Link', 'No Parameter Link'), ('Canceled', 'Canceled'), ('Processing Error', 'Processing Error'), ('External API Error', 'External API Error'), ('Log Entry', 'Log Entry')], default='New', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contacts_prop', models.ForeignKey(blank=True, db_column='contacts_prop_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_delivery_logs_entries', to='exchange.contacts_prop')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_delivery_logs_employees', to='company.employees')),
                ('privser_custom_fields', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_delivery_logs_parameters', to='privser.custom_fields')),
            ],
            options={
                'verbose_name': 'Sync Delivery Log',
                'verbose_name_plural': 'Sync Delivery Logs',
                'indexes': [models.Index(fields=['email'], name='synchroniza_email_7da840_idx'), models.Index(fields=['target_system'], name='synchroniza_target__ce7bec_idx'), models.Index(fields=['updated_at'], name='synchroniza_updated_c062e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Sync_Parameters_Logs',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255)),
                ('property_name', models.CharField(blank=True, max_length=255, null=True)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('old_value_updated', models.DateTimeField(blank=True, null=True)),
                ('new_value_updated', models.DateTimeField(blank=True, null=True)),
                ('source_system', models.CharField(choices=[('privser', 'Privser'), ('exchange', 'Exchange'), ('local', 'Local'), ('NA', 'N/A')], max_length=20)),
                ('target_system', models.CharField(choices=[('privser', 'Privser'), ('exchange', 'Exchange'), ('local', 'Local'), ('NA', 'N/A')], max_length=20)),
                ('body', models.JSONField(blank=True, default=dict, null=True)),
                ('removed', models.BooleanField(default=False)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('status_code', models.SmallIntegerField(choices=[(0, 'Not Processed'), (1, 'Processing'), (5, 'Sync Completed'), (6, 'Ignored'), (7, 'No Data Changes'), (9, 'No Data Links'), (10, 'No Contact Link'), (11, 'No Parameter Link'), (19, 'Canceled'), (400, 'Processing Error'), (404, 'External API Error'), (50, 'Log Entry')], default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact_privser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs_privser', to='privser.contacts')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs_employees', to='company.employees')),
                ('privser_custom_fields', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sync_logs_parameters', to='privser.custom_fields')),
            ],
            options={
                'verbose_name': 'Sync_Parameters_Logs',
                'verbose_name_plural': 'Sync_Parameters_Logs',
                'indexes': [models.Index(fields=['email'], name='synchroniza_email_83f7d1_idx'), models.Index(fields=['target_system'], name='synchroniza_target__cd38ba_idx'), models.Index(fields=['updated_at'], name='synchroniza_updated_e7bc65_idx')],
            },
        ),
    ]
