# Generated by Django 6.0.1 on 2026-01-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_site_form',
            field=models.FileField(blank=True, help_text='Uploaded or generated job site form PDF.', null=True, upload_to='jobs/site_forms/'),
        ),
    ]
