# Generated by Django 5.1.7 on 2025-07-28 02:09

import core.models.SavedFilter
import django.db.models.deletion
import markdownx.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cron_Logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '_Cron: _logs',
                'verbose_name_plural': '_Cron: _logs',
            },
        ),
        migrations.CreateModel(
            name='Documentation_Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, default='untitled', max_length=200, null=True, unique=True)),
                ('content', markdownx.models.MarkdownxField()),
            ],
            options={
                'verbose_name': 'Documentation: Page',
                'verbose_name_plural': 'Documentation: Pages',
            },
        ),
        migrations.CreateModel(
            name='Employee_Last_Updates',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('PRIVSER', 'Privser'), ('EXCHANGE', 'Exchange')], default=None, max_length=50, null=True)),
                ('contact_id', models.CharField(max_length=255)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
                ('date_updated_str', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Import_Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('raw_data', models.JSONField()),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default=None, max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mqtt_Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('raw_data', models.TextField()),
                ('parsed_data', models.JSONField(blank=True, null=True)),
                ('condition_content', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Ok', 'Ok'), ('Pending', 'Pending'), ('Failed', 'Failed')], default='Pending', max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('raw_timestamp', models.BigIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('beacon', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Request_From_Indeed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request', models.JSONField(default=dict)),
                ('status_code', models.SmallIntegerField(choices=[(0, 'New'), (1, 'In Progress'), (5, 'Completed'), (6, 'Ignore'), (19, 'Canceled'), (400, 'Error')], default=0)),
                ('errors', models.JSONField(blank=True, default=dict, null=True)),
                ('critical', models.JSONField(blank=True, default=dict, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Request from Indeed',
                'verbose_name_plural': 'Requests from Indeed',
            },
        ),
        migrations.CreateModel(
            name='Request_From_n8n',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('request', models.JSONField(default=dict)),
                ('status_code', models.SmallIntegerField(choices=[(0, 'New'), (1, 'In Progress'), (5, 'Completed'), (6, 'Ignore'), (19, 'Canceled'), (400, 'Error')], default=0)),
                ('errors', models.JSONField(blank=True, default=dict, null=True)),
                ('critical', models.JSONField(blank=True, default=dict, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Request from n8n',
                'verbose_name_plural': 'Requests from n8n',
            },
        ),
        migrations.CreateModel(
            name='Saved_Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('course_id', models.IntegerField(blank=True, null=True)),
                ('data_type', models.CharField(choices=[('data', 'data'), ('cumulative', 'cumulative')], default='data', max_length=10)),
                ('year_from', models.IntegerField(blank=True, null=True)),
                ('year_to', models.IntegerField(blank=True, null=True)),
                ('chart_type', models.CharField(choices=[('line', 'Line'), ('bar', 'Bar')], default='line', max_length=10)),
                ('display_order', models.IntegerField(default=0)),
                ('dashboard', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_order'],
            },
        ),
        migrations.CreateModel(
            name='Saved_Filter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('params', models.JSONField()),
                ('order', models.IntegerField(default=0)),
                ('columns', models.JSONField(default=core.models.SavedFilter.default_columns)),
                ('columns_main', models.JSONField(default=dict)),
                ('dashboard', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Task_Toggle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Saved_Filter_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.JSONField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fields_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fields', models.JSONField()),
                ('type', models.CharField(blank=True, choices=[('EMPLOYEES_AJAX', 'Employees table'), ('CREWS_ZONES_MODAL', 'Crews zone (modal)')], default=None, max_length=25, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'type'), name='unique_user_type')],
            },
        ),
    ]
