# Generated by Django 5.2.5 on 2025-09-13 00:11

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0026_alter_availability_location_city_and_more'),
        ('core', '0001_initial'),
        ('dispatch', '0017_contracts_company_rel'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpTicket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('status', models.CharField(choices=[('send', 'send'), ('processing', 'processing'), ('completed', 'completed'), ('unresolved', 'unresolved')], default='open', max_length=50, verbose_name='Status')),
                ('priority', models.CharField(choices=[('extreme', 'extreme'), ('high', 'high'), ('mid', 'mid'), ('low', 'low')], default='mid', max_length=50, verbose_name='Priority level')),
                ('document', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='Document')),
                ('date_opened', models.DateTimeField(blank=True, null=True, verbose_name='Date opened')),
                ('date_completed', models.DateTimeField(blank=True, null=True, verbose_name='Date completed')),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets', to='company.employees', verbose_name='Created by')),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_crew', to='company.crew')),
                ('dispatch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_dispatch', to='dispatch.dispatch')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_employee', to='company.employees')),
                ('equipment_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_equipment_group', to='dispatch.equipment_group')),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_phone', to='dispatch.phone')),
                ('radio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_radio', to='dispatch.radio')),
                ('responsible_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responsible_person_tickets', to='company.employees', verbose_name='Responsible person')),
                ('saw', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_saw', to='dispatch.saw')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_truck', to='dispatch.truck')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee'], name='core_helpti_employe_b7ea30_idx'), models.Index(fields=['crew'], name='core_helpti_crew_id_d90785_idx'), models.Index(fields=['dispatch'], name='core_helpti_dispatc_ce5998_idx'), models.Index(fields=['equipment_group'], name='core_helpti_equipme_632b32_idx'), models.Index(fields=['saw'], name='core_helpti_saw_id_3d9d4f_idx'), models.Index(fields=['radio'], name='core_helpti_radio_i_ce7ae5_idx'), models.Index(fields=['phone'], name='core_helpti_phone_i_ca7c73_idx'), models.Index(fields=['truck'], name='core_helpti_truck_i_0ace54_idx'), models.Index(fields=['status', 'priority'], name='core_helpti_status_9a8345_idx')],
            },
        ),
    ]
