# Generated by Django 5.2.5 on 2025-09-14 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_helpticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpticket',
            name='priority',
            field=models.CharField(choices=[('extreme', 'Extreme'), ('high', 'High'), ('mid', 'Middle'), ('low', 'Low'), ('low', 'Low')], default='mid', max_length=50, verbose_name='Priority level'),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='status',
            field=models.CharField(choices=[('send', 'Send'), ('processing', 'Processing'), ('completed', 'Completed'), ('unresolved', 'Unresolved')], default='send', max_length=50, verbose_name='Status'),
        ),
    ]
