# Generated by Django 5.2.5 on 2025-09-14 22:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_helpticket_priority_alter_helpticket_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='helpticket',
            name='created_by_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_tickets_admin', to=settings.AUTH_USER_MODEL, verbose_name='Created by admin'),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='priority',
            field=models.CharField(choices=[('extreme', 'Extreme'), ('high', 'High'), ('mid', 'Middle'), ('low', 'Low')], default='mid', max_length=50, verbose_name='Priority level'),
        ),
    ]
