# Generated by Django 5.2.5 on 2025-09-15 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_employees_user'),
        ('core', '0004_helpticket_created_by_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='helpticket',
            name='responsible_person',
        ),
        migrations.AddField(
            model_name='helpticket',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to_tickets', to='company.employees', verbose_name='Assigned to'),
        ),
        migrations.AddField(
            model_name='helpticket',
            name='created_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_for_tickets', to='company.employees', verbose_name='Created for'),
        ),
    ]
