# Generated by Django 5.2.5 on 2025-09-15 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_helpticket_responsible_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpticket',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Ticket'),
        ),
    ]
