# Generated by Django 5.2.5 on 2025-09-16 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_employees_user'),
        ('core', '0006_helpticket_body'),
        ('dispatch', '0017_contracts_company_rel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='helpticket',
            name='core_helpti_employe_b7ea30_idx',
        ),
        migrations.RemoveIndex(
            model_name='helpticket',
            name='core_helpti_crew_id_d90785_idx',
        ),
        migrations.RemoveField(
            model_name='helpticket',
            name='crew',
        ),
        migrations.RemoveField(
            model_name='helpticket',
            name='employee',
        ),
        migrations.AddField(
            model_name='helpticket',
            name='employees',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_employees', to='company.employees'),
        ),
        migrations.AddField(
            model_name='helpticket',
            name='firecrew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_firecrew', to='company.firecrew'),
        ),
        migrations.AddIndex(
            model_name='helpticket',
            index=models.Index(fields=['employees'], name='core_helpti_employe_8411c0_idx'),
        ),
        migrations.AddIndex(
            model_name='helpticket',
            index=models.Index(fields=['firecrew'], name='core_helpti_firecre_66da85_idx'),
        ),
    ]
