# Generated by Django 5.2.5 on 2025-09-27 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_helpticket_core_helpti_employe_b7ea30_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee_last_updates',
            name='type',
            field=models.CharField(blank=True, choices=[('PRIVSER', 'Privser'), ('EXCHANGE', 'Exchange'), ('PAYCHEX', 'Paychex')], default=None, max_length=50, null=True),
        ),
    ]
