# Generated by Django 5.2.5 on 2025-09-27 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_category_taskcompleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='sort_order',
        ),
    ]
