# Generated by Django 5.2.5 on 2025-09-27 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_task_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('processing', 'Processing'), ('completed', 'Completed')], default='new', max_length=50, verbose_name='Status'),
        ),
    ]
