# Generated by Django 5.2.5 on 2025-10-10 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpticket',
            name='priority',
            field=models.CharField(choices=[('10', '10 (High)'), ('9', '9'), ('8', '8'), ('7', '7'), ('6', '6'), ('5', '5 (Middle)'), ('4', '4'), ('3', '3'), ('2', '2'), ('1', '1 (Low)'), ('-', '-')], default='-', max_length=50, verbose_name='Priority level'),
        ),
    ]
