# Generated by Django 5.2.5 on 2025-10-10 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_helpticket_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpticket',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='help_ticket', to='core.category'),
        ),
    ]
