# Generated by Django 5.2.5 on 2025-10-11 00:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_student_certificate_confirmed'),
        ('core', '0015_helpticket_category'),
        ('dispatch', '0017_contracts_company_rel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='helpticket',
            index=models.Index(fields=['category'], name='core_helpti_categor_f05514_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['category'], name='core_task_categor_cb70f7_idx'),
        ),
    ]
