# Generated by Django 5.2.5 on 2025-10-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_helpticket_core_helpti_categor_f05514_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpticket',
            name='tools',
            field=models.CharField(blank=True, choices=[('supplies', 'Supplies needed'), ('tools', 'Tools needed'), ('both', 'Supplies and tools needed'), ('unknown', 'Unknown'), ('none', 'No supplies or tools needed')], default='', max_length=32, verbose_name='Supplies/tools'),
        ),
    ]
