# Generated by Django 5.2.5 on 2025-10-22 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_helpticket_tools'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpticket',
            name='priority',
            field=models.CharField(choices=[('10', '10 (High)'), ('09', '9'), ('08', '8'), ('07', '7'), ('06', '6'), ('05', '5 (Middle)'), ('04', '4'), ('03', '3'), ('02', '2'), ('01', '1 (Low)'), ('-', '-')], default='-', max_length=50, verbose_name='Priority level'),
        ),
    ]
