# Generated by Django 5.2.5 on 2025-10-22 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_employees_parameters_value_array'),
        ('core', '0018_alter_helpticket_priority'),
        ('dispatch', '0018_contracts_per_dof_hr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='helpticket',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.helpticket', verbose_name='Parent ticket'),
        ),
        migrations.AddIndex(
            model_name='helpticket',
            index=models.Index(fields=['parent'], name='core_helpti_parent__69f0df_idx'),
        ),
    ]
