# Generated by Django 5.2.5 on 2025-10-23 02:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '0036_employees_parameters_value_array'),
        ('core', '0019_helpticket_parent_and_more'),
        ('dispatch', '0018_contracts_per_dof_hr'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='helpticket',
            name='core_helpti_parent__69f0df_idx',
        ),
        migrations.AddField(
            model_name='helpticket',
            name='assigned_to_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_group_tickets', to='auth.group', verbose_name='Assigned to group'),
        ),
        migrations.AddIndex(
            model_name='helpticket',
            index=models.Index(fields=['assigned_to_group'], name='core_helpti_assigne_a2e09f_idx'),
        ),
    ]
