# Generated by Django 5.2.5 on 2025-10-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_helpticket_core_helpti_parent__69f0df_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Import_Dayonfire_Row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(blank=True, default=None, max_length=50, null=True)),
                ('raw_data', models.JSONField()),
                ('status', models.CharField(choices=[('OK', 'Ok'), ('PENDING', 'Pending'), ('FAILED', 'Failed')], default=None, max_length=20)),
                ('error', models.TextField(blank=True, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
