# Generated by Django 5.2.5 on 2025-12-02 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_import_dayonfire_row'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminInlineConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inline_class_name', models.CharField(help_text="Exact class name of the inline (e.g., 'FireRunInline')", max_length=100, unique=True)),
                ('fields_config', models.JSONField(blank=True, default=list, help_text="List of field names to display. Example: ['field1', 'field2']")),
                ('readonly_fields_config', models.JSONField(blank=True, default=list, help_text="List of readonly field names. Example: ['field1', 'field2']")),
                ('notes', models.TextField(blank=True, help_text='Optional notes about this configuration')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Admin Inline Configuration',
                'verbose_name_plural': 'Admin Inline Configurations',
                'ordering': ['inline_class_name'],
            },
        ),
    ]
