# Generated by Django 5.2.5 on 2025-12-03 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_admininlineconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='helpticket',
            name='status',
            field=models.CharField(choices=[('send', 'Not started'), ('processing', 'Started'), ('completed', 'Finished'), ('unresolved', 'Unable to complete')], default='send', max_length=50, verbose_name='Status'),
        ),
    ]
