# Generated by Django 5.2.5 on 2025-12-11 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('company', '0047_banktransaction'),
        ('core', '0023_alter_helpticket_status'),
        ('dispatch', '0021_remove_equipment_dynamic_parameters_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='helpticket',
            name='prerequisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dependent_tickets', to='core.helpticket', verbose_name='Prerequisite ticket'),
        ),
        migrations.AlterField(
            model_name='helpticket',
            name='status',
            field=models.CharField(choices=[('send', 'Not started'), ('processing', 'Started'), ('completed', 'Finished'), ('unresolved', 'Unable to complete'), ('waiting', 'Waiting for other tasks')], default='send', max_length=50, verbose_name='Status'),
        ),
        migrations.AddIndex(
            model_name='helpticket',
            index=models.Index(fields=['prerequisite'], name='core_helpti_prerequ_7f9314_idx'),
        ),
    ]
