# Generated by Django 5.2.5 on 2025-12-12 02:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_add_prerequisite_to_helpticket'),
        ('dispatch', '0021_remove_equipment_dynamic_parameters_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpticket',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tickets_as_equipment', to='dispatch.equipment'),
        ),
    ]
