# Generated by Django 6.0.1 on 2026-01-27 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='invoice_pdf',
            field=models.FileField(blank=True, help_text='Uploaded or generated PDF for this invoice.', null=True, upload_to='invoices/pdfs/'),
        ),
    ]
