# Generated by Django 6.0.1 on 2026-03-27 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_calls', '0009_ghlcall_raw_started_at_ghlcall_raw_ended_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='promptspec',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='promptspec',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
