# Generated by Django 6.0 on 2026-03-28 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_calls', '0011_seed_default_prompt_spec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ghlcall',
            name='audio_file',
        ),
    ]
