# Generated by Django 6.0 on 2026-03-31 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghl_calls', '0012_remove_ghlcall_audio_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='GHLCallTranscriptBulkEdit',
            fields=[
            ],
            options={
                'verbose_name': 'Transcript Bulk Edit',
                'verbose_name_plural': 'Transcript Bulk Edit',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ghl_calls.ghlcall',),
        ),
        migrations.CreateModel(
            name='QuestionGroupingReview',
            fields=[
            ],
            options={
                'verbose_name': 'Question Grouping Review',
                'verbose_name_plural': 'Question Grouping Review',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('ghl_calls.question',),
        ),
        migrations.CreateModel(
            name='UnifiedNodeAnswerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unified_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='ghl_calls.unifiednodeanswer')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnifiedNodeQuestionAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unified_question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='ghl_calls.unifiednodequestion')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnifiedNodeStatementAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unified_statement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='ghl_calls.unifiednodestatement')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
