# Generated by Django 5.1.7 on 2025-07-28 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='company',
            field=models.CharField(blank=True, choices=[('Dust Busters Plus LLC', 'Dust Busters Plus LLC'), ('Idaho Land Services LLC', 'Idaho Land Services LLC'), ('DBP South LLC', 'DBP South LLC'), ('Southern Solutions LLC', 'Southern Solutions LLC')], max_length=25, null=True, verbose_name='Company'),
        ),
    ]
