# Generated by Django 5.1.7 on 2025-07-29 00:47

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_dispatch_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_date', models.DateField(blank=True, null=True, verbose_name='Invoice Date')),
                ('status', models.CharField(blank=True, choices=[('Paid-Check in the mail', 'Paid-Check in the mail'), ('Approved for payment', 'Approved for payment'), ('Ready for approval', 'Ready for approval'), ('In progress', 'In progress'), ('Waiting for Final Invoice', 'Waiting for Final Invoice'), ('Canceled', 'Canceled'), ('Missing', 'Missing'), ('IRA Crews', 'IRA Crews')], max_length=100, null=True, verbose_name='Status')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Start Date')),
                ('finish_date', models.DateField(blank=True, null=True, verbose_name='Finish Date')),
                ('number_of_days', models.PositiveIntegerField(blank=True, null=True, verbose_name='Number Of Days')),
                ('invoice_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Invoice Amount')),
                ('invoice_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Invoice Number')),
                ('date_paid', models.DateField(blank=True, null=True, verbose_name='Date Paid')),
                ('check_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Check Amount')),
                ('change_in_payment', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Change in Payment')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='File')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('dispatch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices_entries', to='dispatch.dispatch', verbose_name='Dispatch')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
    ]
