# Generated by Django 5.1.7 on 2025-07-29 03:02

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='dot_inspection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Dot Inspection Date'),
        ),
        migrations.AddField(
            model_name='truck',
            name='dot_inspection_file',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='Dot Inspection File'),
        ),
        migrations.AddField(
            model_name='truck',
            name='drive',
            field=models.CharField(blank=True, choices=[('4x4', '4x4'), ('2x4', '2x4'), ('6x6', '6x6'), ('4x6', '4x6')], max_length=100, null=True, verbose_name='Drive'),
        ),
        migrations.AddField(
            model_name='truck',
            name='motor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Motor'),
        ),
        migrations.AddField(
            model_name='truck',
            name='number_of_doors',
            field=models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Number of doors'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(blank=True, choices=[('Paid', 'Paid'), ('Paid-Check in the mail', 'Paid-Check in the mail'), ('Approved for payment', 'Approved for payment'), ('Ready for approval', 'Ready for approval'), ('In progress', 'In progress'), ('Waiting for Final Invoice', 'Waiting for Final Invoice'), ('Canceled', 'Canceled'), ('Missing', 'Missing'), ('IRA Crews', 'IRA Crews')], max_length=100, null=True, verbose_name='Status'),
        ),
    ]
