# Generated by Django 5.1.7 on 2025-07-29 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_truck_dot_inspection_date_truck_dot_inspection_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='camp_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Camp location'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='working_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Working location'),
        ),
    ]
