# Generated by Django 5.1.7 on 2025-07-29 03:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_crew_options'),
        ('dispatch', '0005_dispatch_camp_location_dispatch_working_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='crew_boss_alternate_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_as_alternate_2_entries', to='company.employees', verbose_name='Crew Boss Alternate #2'),
        ),
        migrations.AlterField(
            model_name='contracts',
            name='crew_boss_alternate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_as_alternate_entries', to='company.employees', verbose_name='Crew Boss Alternate #1'),
        ),
    ]
