# Generated by Django 5.1.7 on 2025-08-01 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0006_contracts_crew_boss_alternate_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='first_operational_period',
            field=models.DateField(blank=True, null=True, verbose_name='First operational period'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='fourteenth_operational_period',
            field=models.DateField(blank=True, null=True, verbose_name='14th operational period'),
        ),
    ]
