# Generated by Django 5.1.7 on 2025-08-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_fire_activity_code_fire_fire_size_fire_fuel_type_and_more'),
        ('dispatch', '0007_dispatch_first_operational_period_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['crew', 'updated_at'], name='dispatch_di_crew_id_708ed6_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatch',
            index=models.Index(fields=['status'], name='dispatch_di_status_873d01_idx'),
        ),
    ]
