# Generated by Django 5.1.7 on 2025-08-08 20:06

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0008_dispatch_dispatch_di_crew_id_708ed6_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='full_contract',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='Full Contract'),
        ),
    ]
