# Generated by Django 5.1.7 on 2025-08-08 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0009_contracts_full_contract'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='equipment_group',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='equipment_group',
            field=models.ManyToManyField(blank=True, related_name='dispatch_entries', to='dispatch.equipment_group'),
        ),
    ]
