# Generated by Django 5.2.5 on 2025-08-21 20:45

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0010_remove_dispatch_equipment_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispatchInvoicesProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Finance tracking',
                'verbose_name_plural': 'Finance tracking',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dispatch.dispatch',),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='payroll_date',
            field=models.DateField(blank=True, null=True, verbose_name='Payroll Run'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='payroll_ready',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='Payroll Ready'),
        ),
    ]
