# Generated by Django 5.2.5 on 2025-08-22 02:29

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0011_dispatchinvoicesproxy_dispatch_payroll_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='payroll_date',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='payroll_run',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='Payroll Run'),
        ),
    ]
