# Generated by Django 5.2.5 on 2025-08-26 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0012_remove_dispatch_payroll_date_dispatch_payroll_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='notes_finance',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='status_finance',
            field=models.CharField(blank=True, choices=[('Needs invoice', 'Needs invoice'), ('Multiple invoices', 'Multiple invoices')], max_length=25, null=True, verbose_name='Status'),
        ),
    ]
