# Generated by Django 5.2.5 on 2025-08-27 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_remove_employees_i9'),
        ('dispatch', '0013_dispatch_notes_finance_dispatch_status_finance'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='crew_archived',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_archived_entries', to='company.firecrew', verbose_name='Crew (archived)'),
        ),
    ]
