# Generated by Django 5.2.5 on 2025-08-27 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_remove_employees_i9'),
        ('dispatch', '0014_dispatch_crew_archived'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='dispatch',
            constraint=models.UniqueConstraint(fields=('crew',), name='uniq_dispatch_crew'),
        ),
        migrations.AddConstraint(
            model_name='dispatch',
            constraint=models.CheckConstraint(condition=models.Q(('crew__isnull', False), ('crew_archived__isnull', False), _negated=True), name='no_crew_and_archived_together'),
        ),
    ]
