# Generated by Django 5.2.5 on 2025-09-04 16:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_company_delete_companies'),
        ('dispatch', '0015_dispatch_uniq_dispatch_crew_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispatch',
            name='company_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispatch_entries', to='company.company', verbose_name='Company'),
        ),
    ]
