# Generated by Django 5.2.5 on 2025-09-04 17:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_company_delete_companies'),
        ('dispatch', '0016_dispatch_company_rel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='company_rel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_entries', to='company.company', verbose_name='Company'),
        ),
    ]
