# Generated by Django 5.2.5 on 2025-10-22 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0017_contracts_company_rel'),
    ]

    operations = [
        migrations.AddField(
            model_name='contracts',
            name='per_dof_hr',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='$ per DOF HR'),
        ),
    ]
