# Generated by Django 5.2.5 on 2025-11-24 22:20

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0018_contracts_per_dof_hr'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Type name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('fields_config', models.JSONField(blank=True, default=list, help_text='List of field names to display for this equipment type. Example: ["power", "rpm", "weight"]', verbose_name='Fields configuration')),
            ],
            options={
                'verbose_name': 'Equipment Type',
                'verbose_name_plural': 'Equipment Types',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial number')),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('imei', models.CharField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=25, null=True)),
                ('pin', models.CharField(blank=True, max_length=25, null=True)),
                ('os', models.CharField(blank=True, choices=[('IOS', 'IOS'), ('Android', 'Android')], max_length=50, null=True)),
                ('key', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Tr#')),
                ('make', models.CharField(blank=True, max_length=100, null=True, verbose_name='Make')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='Model')),
                ('license_plate', models.CharField(blank=True, max_length=50, null=True, verbose_name='License plate')),
                ('owner', models.CharField(blank=True, choices=[('Enterprise', 'Enterprise'), ('United', 'United'), ('Flex', 'Flex'), ('Fleet', 'Fleet'), ('Other', 'Other'), ('owned', 'owned'), ('leased', 'leased'), ('rented', 'rented'), ('personal', 'personal')], max_length=50, null=True, verbose_name='Owner')),
                ('year', models.IntegerField(blank=True, null=True, verbose_name='Year')),
                ('milage', models.IntegerField(blank=True, null=True, verbose_name='Milage')),
                ('passengers', models.IntegerField(blank=True, null=True, verbose_name='Passengers')),
                ('picture', models.ImageField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='Picture')),
                ('vin_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='VIN number')),
                ('gvwr', models.CharField(blank=True, max_length=100, null=True, verbose_name='gvwr')),
                ('color', models.CharField(blank=True, max_length=100, null=True, verbose_name='Color')),
                ('fuel_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fuel type')),
                ('insurance_expiration_date', models.DateField(blank=True, null=True, verbose_name='Insurance exp date')),
                ('registration_expiration_date', models.DateField(blank=True, null=True, verbose_name='Registration exp date')),
                ('next_service_date', models.DateField(blank=True, null=True, verbose_name='Next service date')),
                ('insurance_provider', models.CharField(blank=True, max_length=100, null=True, verbose_name='Insurance provider')),
                ('registration_state', models.CharField(blank=True, max_length=100, null=True, verbose_name='Registration state')),
                ('number_of_doors', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='Number of doors')),
                ('drive', models.CharField(blank=True, choices=[('4x4', '4x4'), ('2x4', '2x4'), ('6x6', '6x6'), ('4x6', '4x6')], max_length=100, null=True, verbose_name='Drive')),
                ('motor', models.CharField(blank=True, max_length=255, null=True, verbose_name='Motor')),
                ('dot_inspection_date', models.DateField(blank=True, null=True, verbose_name='Dot Inspection Date')),
                ('dot_inspection_file', models.ImageField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='Dot Inspection File')),
                ('needs_maintenance', models.BooleanField(default=False, verbose_name='Needs maintenance')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='QR Code')),
                ('nomex_type', models.CharField(blank=True, choices=[('Pants', 'Pants'), ('Shirt', 'Shirt')], max_length=50, null=True)),
                ('condition', models.CharField(blank=True, choices=[('New', 'New'), ('Excellent', 'Excellent'), ('Good', 'Good'), ('Usable', 'Usable'), ('Barely Usable', 'Barely Usable'), ('Needs Repair', 'Needs Repair'), ('Not repairable', 'Not repairable')], max_length=50, null=True)),
                ('status', models.CharField(blank=True, choices=[('On Fire', 'On Fire'), ('Not On Fire', 'Not On Fire'), ('Scheduled', 'Scheduled')], max_length=25, null=True, verbose_name='Status')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment_group', models.ManyToManyField(blank=True, related_name='equipment_entries', to='dispatch.equipment_group')),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='dispatch.equipmenttype', verbose_name='Equipment type')),
            ],
            options={
                'verbose_name': 'Equipment',
                'verbose_name_plural': 'Equipment',
                'ordering': ['name'],
            },
        ),
    ]
