# Generated by Django 5.2.5 on 2025-11-24 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0019_equipmenttype_equipment'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='dynamic_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Stores dynamic parameter values based on equipment type configuration', verbose_name='Dynamic parameters'),
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='fields_config',
            field=models.JSONField(blank=True, default=list, help_text='List of field definitions. Example: [{"name": "power", "type": "CharField", "label": "Power"}, {"name": "rpm", "type": "IntegerField", "label": "RPM"}]', verbose_name='Fields configuration'),
        ),
    ]
