# Generated by Django 5.2.5 on 2025-11-24 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0020_equipment_dynamic_parameters_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='dynamic_parameters',
        ),
        migrations.AlterField(
            model_name='equipmenttype',
            name='fields_config',
            field=models.JSONField(blank=True, default=list, help_text='List of field names to display for this equipment type. Example: ["power", "rpm", "weight"]', verbose_name='Fields configuration'),
        ),
    ]
