# Generated by Django 5.2.5 on 2025-12-12 22:01

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0021_remove_equipment_dynamic_parameters_and_more'),
        ('privser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InspectionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Type name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Inspection Type',
                'verbose_name_plural': 'Inspection Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(blank=True, help_text='Inspection file/document', null=True, upload_to=core.utils.model_directory_path, verbose_name='File')),
                ('date', models.DateField(blank=True, help_text='Inspection date', null=True, verbose_name='Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('equipment', models.ForeignKey(blank=True, help_text='Relation to equipment', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='dispatch.equipment', verbose_name='Equipment')),
                ('inspector', models.ForeignKey(blank=True, help_text='Inspector can be a relation to a contact', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections', to='privser.contacts', verbose_name='Inspector')),
                ('inspection_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspections', to='dispatch.inspectiontype', verbose_name='Inspection type')),
            ],
            options={
                'verbose_name': 'Inspection',
                'verbose_name_plural': 'Inspections',
                'ordering': ['-date', '-updated_at'],
            },
        ),
    ]
