# Generated by Django 5.2.5 on 2025-12-12 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0022_create_inspections'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontype',
            name='eav_attributes_config',
            field=models.JSONField(blank=True, default=list, help_text='List of EAV attribute slugs to display for this inspection type. Example: ["mileage", "condition", "notes"]', verbose_name='EAV Attributes configuration'),
        ),
    ]
