# Generated by Django 5.2.5 on 2025-12-13 00:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dispatch', '0023_add_eav_attributes_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inspection',
            name='equipment',
        ),
        migrations.CreateModel(
            name='InspectionRelatedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='Related object ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Related object type')),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_items', to='dispatch.inspection', verbose_name='Inspection')),
            ],
            options={
                'verbose_name': 'Related Item',
                'verbose_name_plural': 'Related Items',
                'ordering': ['-updated_at'],
            },
        ),
    ]
