# Generated by Django 6.0.1 on 2026-02-12 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearndashCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_course_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearndashUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_user_id', models.PositiveBigIntegerField(db_index=True, unique=True)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LearndashLessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wp_lesson_id', models.PositiveBigIntegerField(db_index=True)),
                ('lesson_name', models.CharField(blank=True, default='', max_length=255)),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_completions', to='learndash_webhook.learndashcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_completions', to='learndash_webhook.learndashuser')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'course'], name='learndash_w_user_id_fa396c_idx'), models.Index(fields=['user', 'wp_lesson_id'], name='learndash_w_user_id_6536de_idx'), models.Index(fields=['course', 'completed_at'], name='learndash_w_course__40775f_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'course', 'wp_lesson_id'), name='uniq_lesson_completion_user_course_lesson')],
            },
        ),
        migrations.CreateModel(
            name='LearndashCourseCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_completions', to='learndash_webhook.learndashcourse')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_completions', to='learndash_webhook.learndashuser')),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'course'], name='learndash_w_user_id_9d4bee_idx'), models.Index(fields=['course', 'completed_at'], name='learndash_w_course__83726a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'course'), name='uniq_course_completion_user_course')],
            },
        ),
    ]
