# Generated by Django 5.1.7 on 2025-07-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts_Prop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('property_name', models.CharField(max_length=255, unique=True)),
                ('property_type', models.CharField(blank=True, choices=[('String', 'String'), ('SystemTime', 'SystemTime'), ('Double', 'Double'), ('Bool', 'Bool'), ('Document', 'Document')], max_length=50, null=True)),
                ('property_tag', models.CharField(blank=True, max_length=50, null=True)),
                ('property_set_id', models.CharField(blank=True, max_length=100, null=True)),
                ('datetime_format', models.CharField(blank=True, max_length=50, null=True)),
                ('visibility', models.BooleanField(default=False)),
                ('param_mirror', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property',
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='ContactsExchange',
            fields=[
            ],
            options={
                'verbose_name': 'Employee params',
                'verbose_name_plural': 'Employees params',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('company.employees',),
        ),
    ]
