# Generated by Django 5.2.5 on 2025-10-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts_prop',
            name='property_type',
            field=models.CharField(blank=True, choices=[('String', 'String'), ('SystemTime', 'SystemTime'), ('Double', 'Double'), ('Bool', 'Bool'), ('Document', 'Document'), ('Array', 'Array')], max_length=50, null=True),
        ),
    ]
