# Generated by Django 5.2.5 on 2025-12-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchange', '0002_alter_contacts_prop_property_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('contact_id', models.CharField(max_length=255)),
                ('last_modified_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified_time', models.DateTimeField()),
                ('status_code', models.SmallIntegerField(choices=[(0, 'New'), (1, 'In Progress'), (5, 'Completed'), (19, 'Canceled'), (400, 'Error')], default=0)),
                ('test', models.SmallIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': ' Contact',
                'verbose_name_plural': ' Contacts',
                'constraints': [models.UniqueConstraint(fields=('email', 'contact_id'), name='unique_email_contact_exchange')],
            },
        ),
        migrations.CreateModel(
            name='ChangesInContacts',
            fields=[
            ],
            options={
                'verbose_name': 'Changes in contacts',
                'verbose_name_plural': 'Changes in contacts',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('exchange.contacts',),
        ),
    ]
