"""
Django settings for core project.

Generated by "django-admin startproject" using Django 5.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from datetime import timedelta
from importlib.util import find_spec

import environ
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / "subdir".
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()
env.read_env(BASE_DIR / ".env")


def env_first(names, default=None):
    for name in names:
        value = os.environ.get(name)
        if value not in (None, ""):
            return value
    return default


def env_bool_multi(names, default=False):
    raw = env_first(names, "1" if default else "0")
    return str(raw).strip().lower() in ("1", "true", "yes", "y", "on")


def env_list_multi(names, default):
    raw = env_first(names, ",".join(default))
    return [item.strip() for item in str(raw).split(",") if item.strip()]

SPECIAL_USERS = ["admin", "dima", "csnortland", "operations"]

MANUALS_DIR = BASE_DIR / "docs"

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env_first(
    ("DJANGO_SECRET_KEY", "SECRET_KEY"),
    "django-insecure-*c5#jqyx=sjk=5y*zvl3t28472!fm9lxtjc9tz2b)zy2!rg8ko",
)

EXTERNAL_API_TOKEN = env("EXTERNAL_API_TOKEN")

# SECURITY WARNING: don"t run with debug turned on in production!
DEBUG = env_bool_multi(("DEBUG", "DJANGO_DEBUG"), default=False)
REDIS_URL = env("REDIS_URL", default="redis://localhost:6379")

FILE_UPLOAD_MAX_MEMORY_SIZE = 524288000  # 500MB
DATA_UPLOAD_MAX_NUMBER_FIELDS = None
DATA_UPLOAD_MAX_NUMBER_FILES = None
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
SECURE_SSL_REDIRECT = env_bool_multi(
    ("DJANGO_SECURE_SSL_REDIRECT", "SECURE_SSL_REDIRECT"),
    default=False,
)
SESSION_COOKIE_SECURE = (not DEBUG) and SECURE_SSL_REDIRECT
CSRF_COOKIE_SECURE = (not DEBUG) and SECURE_SSL_REDIRECT
CSRF_TRUSTED_ORIGINS = env_list_multi(
    ("DJANGO_CSRF_TRUSTED_ORIGINS",),
    ["https://prod.vectorops.xyz"],
)
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = env_first(("DJANGO_REFERRER_POLICY",), "same-origin")
X_FRAME_OPTIONS = env_first(("DJANGO_X_FRAME_OPTIONS",), "SAMEORIGIN")

ALLOWED_HOSTS = env_list_multi(
    ("DJANGO_ALLOWED_HOSTS", "ALLOWED_HOSTS"),
    ["127.0.0.1", "localhost", "prod.vectorops.xyz", "52.88.131.53"],
)
LANGUAGE_CODE = "en-us"
TIME_ZONE = "America/Los_Angeles"
USE_I18N = True
USE_TZ = True
FORMAT_MODULE_PATH = ["core.formats"]

LOGIN_URL = "/login/"
LOGIN_REDIRECT_URL = "/login/"

GRAPPELLI_INDEX_DASHBOARD = "core.dashboard.CustomIndexDashboard"
GRAPPELLI_ADMIN_TITLE = "Dust Busters Plus LLC"
# GRAPPELLI_AUTOCOMPLETE_LIMIT = 10
# GRAPPELLI_AUTOCOMPLETE_SEARCH_FIELDS = {}
# GRAPPELLI_CLEAN_INPUT_TYPES = True


PRIVSER_API2_URL = env("PRIVSER_API2_URL", default=None)
PRIVSER_API2_KEY = env("PRIVSER_API2_KEY", default=None)
PRIVSER_LOCATION_ID = env("PRIVSER_LOCATION_ID", default=None)

PRIVSER_URL = env("PRIVSER_URL", default=None)
PRIVSER_API_KEY = env("PRIVSER_API_KEY", default=None)

URL_SENT_CHANGED_PARAMETERS = env("URL_SENT_CHANGED_PARAMETERS", default=None)

MQTT_HOST = env("MQTT_HOST", default=None)
MQTT_USER = env("MQTT_USER", default=None)
MQTT_PASS = env("MQTT_PASS", default=None)

PAYCHEX_COMPANY_ID = env("PAYCHEX_COMPANY_ID", default=None)
PAYCHEX_CLIENT_ID = env("PAYCHEX_CLIENT_ID", default=None)
PAYCHEX_CLIENT_SECRET = env("PAYCHEX_CLIENT_SECRET", default=None)
PAYCHEX_BASE_URL = env("PAYCHEX_BASE_URL", default=None)

FLEXTIME_BASE_URL = env("FLEXTIME_BASE_URL", default=None)
FLEXTIME_CUSTOMER_ALIAS = env("FLEXTIME_CUSTOMER_ALIAS", default=None)
FLEXTIME_SHARED_KEY = env("FLEXTIME_SHARED_KEY", default=None)
FLEXTIME_WSPASS = env("FLEXTIME_WSPASS", default=None)
FLEXTIME_TZ = env("FLEXTIME_TZ", default=None)
FLEXTIME_TOKEN_TTL = env.int("FLEXTIME_TOKEN_TTL", default=5400)

GHL_CLIENT_ID = env("GHL_CLIENT_ID", default="")
GHL_CLIENT_SECRET = env("GHL_CLIENT_SECRET", default="")
GHL_REDIRECT_URI = env("GHL_REDIRECT_URI", default="")
GHL_VERSION_ID = env("GHL_VERSION_ID", default="2021-07-28")
GHL_DJANGO_CONTACT_ID_FIELD_ID = env("GHL_DJANGO_CONTACT_ID_FIELD_ID", default="")
GHL_LOCATION_ID = env("GHL_LOCATION_ID", default="")
GHL_DEFAULT_COMPANY_NAME = env("GHL_DEFAULT_COMPANY_NAME", default="Dust Busters Plus LLC")
GHL_DEFAULT_CONTACT_ROLE = env("GHL_DEFAULT_CONTACT_ROLE", default="employee")
GHL_WEBHOOK_PUBLIC_KEY = env("GHL_WEBHOOK_PUBLIC_KEY", default="")
GHL_WEBHOOK_LEGACY_PUBLIC_KEY = env("GHL_WEBHOOK_LEGACY_PUBLIC_KEY", default="")
GHL_CALLS_ALLOW_UNSIGNED_WEBHOOKS = env.bool("GHL_CALLS_ALLOW_UNSIGNED_WEBHOOKS", default=False)
GHL_DJANGO_COMPANY_FIELD_ID = env("GHL_DJANGO_COMPANY_FIELD_ID", default="")
GHL_DJANGO_ROLE_FIELD_ID = env_first(("GHL_DJANGO_ROLE_FIELD_ID", "GHL_DJANGO_Role_ID"), "")
GHL_DJANGO_Role_ID = GHL_DJANGO_ROLE_FIELD_ID

LD_WEBHOOK_SECRET = env("LD_WEBHOOK_SECRET", default="")
LEARNDASH_BASE_URL = env("LEARNDASH_BASE_URL", default="")
LEARNDASH_USERNAME = env("LEARNDASH_USERNAME", default="")
LEARNDASH_APP_PASSWORD = env("LEARNDASH_APP_PASSWORD", default="")

EXCHANGE_PRIMARY_SMTP_ADDRESS = env("EXCHANGE_PRIMARY_SMTP_ADDRESS", default=None)
EXCHANGE_USERNAME = env("EXCHANGE_USERNAME", default=None)
EXCHANGE_PASSWORD = env("EXCHANGE_PASSWORD", default=None)
EXCHANGE_PROPERTY_SET_ID_CONF = env("EXCHANGE_PROPERTY_SET_ID_CONF", default=None)
EXCHANGE_FOLDER_PATH = env("EXCHANGE_FOLDER_PATH", default=None)

WEBPUSH_SETTINGS = {
    # Need to move this to env, but again there's no time for it!
    # Base64 URL-safe public key for use in JS (webpush.js / webpush_header)
    "VAPID_PUBLIC_KEY": (
        "BOoEQVkoJWGgQz1QlmG06lkD0KMSKaU8tppuD8svuO1VHshW2rrA-8XhDQVARAtBDaf_"
        "rwCa0d7oDMNqCcsN0xI"
    ),
    # Base64 URL-safe private key string used on the server side to sign notifications
    "VAPID_PRIVATE_KEY": (
        "MIGHAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBG0wawIBAQQgU7aXX0LcHoMqTgaUEYce"
        "eGYxXNlcV-kR-WN0dwozlKihRANCAATqBEFZKCVhoEM9UJZhtOpZA9CjEimlPLaabg_L"
        "L7jtVR7IVtq6wPvF4Q0FQEQLQQ2n_68AmtHe6AzDagnLDdMS"
    ),
    "VAPID_ADMIN_EMAIL": "admin@example.com",
}

INSTALLED_APPS = [
    "dal",
    "dal_select2",
    "django.contrib.contenttypes",
    "grappelli.dashboard",
    "grappelli",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_admin_flexlist",
    "core",
    "axes",
    "more_admin_filters",
    "rangefilter",
    "django_extensions",
    "dalf",
    "sorl.thumbnail",
    "django_celery_results",
    "ajax_datatable",
    "core.admin_panel",
    "exchange",
    "company",
    "attendance",
    "privser",
    "synchronization",
    "paychex",
    "dispatch",
    "markdownx",
    "rest_framework",
    "frontend",
    "pwa_vehicle",
    "pwa_crwb",
    "pwa_notifications",
    "checkin_pwa",
    "evernote_pwa",
    "companies",
    "contacts",
    "pic_pwa",
    "id_scanner",
    "jobs",
    "invoices",
    "integrations",
    "ghl_calls",
    "learndash",
    "learndash_webhook.app.LearndashWebhookConfig",
    "automations",
    "import_export",
    "treebeard",
    "webpush",
    "eav",
    "pdf_plugin",
]

USE_WHITENOISE = env_bool_multi(("DJANGO_USE_WHITENOISE",), default=False)

# if DEBUG and find_spec("django_extensions"):
# INSTALLED_APPS.append("django_extensions")

THUMBNAIL_DEBUG = False  # отключает лишний мусор в логах
THUMBNAIL_KVSTORE = "sorl.thumbnail.kvstores.cached_db_kvstore.KVStore"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    # 'django.middleware.locale.LocaleMiddleware',
    "django.middleware.csrf.CsrfViewMiddleware",  # I ruled it out myself for Forbidden (CSRF cookie not set.)
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "core.middleware.CurrentUserMiddleware",
    "axes.middleware.AxesMiddleware",
]

if USE_WHITENOISE and find_spec("whitenoise"):
    MIDDLEWARE.insert(1, "whitenoise.middleware.WhiteNoiseMiddleware")

AUTHENTICATION_BACKENDS = [
    "axes.backends.AxesStandaloneBackend",
    "django.contrib.auth.backends.ModelBackend",
]

INTERNAL_IPS = []

if DEBUG and find_spec("debug_toolbar"):
    # INSTALLED_APPS.insert(0, "debug_toolbar")
    # MIDDLEWARE.insert(0, "debug_toolbar.middleware.DebugToolbarMiddleware")
    INTERNAL_IPS = ["127.0.0.1", "::1"]

# DEBUG_TOOLBAR_PANELS = [
#     "debug_toolbar.panels.versions.VersionsPanel",
#     "debug_toolbar.panels.timer.TimerPanel",
#     "debug_toolbar.panels.settings.SettingsPanel",
#     "debug_toolbar.panels.headers.HeadersPanel",
#     "debug_toolbar.panels.request.RequestPanel",
#     "debug_toolbar.panels.sql.SQLPanel",
#     "debug_toolbar.panels.templates.TemplatesPanel",
#     "debug_toolbar.panels.staticfiles.StaticFilesPanel",
#     "debug_toolbar.panels.cache.CachePanel",
#     "debug_toolbar.panels.signals.SignalsPanel",
#     "debug_toolbar.panels.logging.LoggingPanel",
#     "debug_toolbar.panels.redirects.RedirectsPanel",
#     # "debug_toolbar.panels.profiling.ProfilingPanel",  ← отключена
# ]

# DEBUG_TOOLBAR_CONFIG = {
#     "SHOW_TOOLBAR_CALLBACK": lambda request: True,  # не забудь это
#     "SHOW_COLLAPSED": True,
#     "INTERCEPT_REDIRECTS": False,
# }

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        # "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            # "debug": True,
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"
# GRAPPELLI_INDEX_DASHBOARD_DEBUG = True
# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases
db_engine_setting = env_first(("DB_ENGINE", "DJANGO_DB_ENGINE"), "sqlite").strip().lower()

if db_engine_setting in {"mysql", "django.db.backends.mysql"}:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": env_first(("DB_NAME", "DJANGO_DB_NAME"), "dbfightfire"),
            "USER": env_first(("DB_USER", "DJANGO_DB_USER"), "root"),
            "PASSWORD": env_first(("DB_PASSWORD", "DJANGO_DB_PASSWORD"), ""),
            "HOST": env_first(("DB_HOST", "DJANGO_DB_HOST"), "127.0.0.1"),
            "PORT": env_first(("DB_PORT", "DJANGO_DB_PORT"), "3306"),
            "OPTIONS": {
                "charset": "utf8mb4",
            },
        },
        "main": {
            "ENGINE": "django.db.backends.mysql",
            "NAME": "dbfightfire",
            "USER": "ChloeApp",
            "PASSWORD": "ChloeAppPaSsWord#1",
            "HOST": "172.31.46.248",
            "PORT": "3306",
            "OPTIONS": {
                "charset": "utf8mb4",
            },
        },
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/
STATIC_URL = "/static/"
STATIC_ROOT = Path(env_first(("DJANGO_STATIC_ROOT",), str(BASE_DIR / "static")))

if USE_WHITENOISE and find_spec("whitenoise"):
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# OCR
default_tesseract_cmd = "tesseract"
windows_tesseract_path = r"C:\Users\cyafei\AppData\Local\Programs\Tesseract-OCR\tesseract.exe"
if os.name == "nt" and os.path.exists(windows_tesseract_path):
    default_tesseract_cmd = windows_tesseract_path

TESSERACT_CMD = os.environ.get("TESSERACT_CMD", default_tesseract_cmd)

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
#         'LOCATION': BASE_DIR / 'cache/thumbnails',
#         'TIMEOUT': None,
#     }
# }

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_URL}/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,
        },
    },
    "axes": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": f"{REDIS_URL}/2",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "IGNORE_EXCEPTIONS": True,
        },
    },
}
AXES_CACHE = "axes"

AXES_ENABLED = True
AXES_LOCKOUT_PARAMETERS = [["ip_address", "username"]]
AXES_FAILURE_LIMIT = 5
AXES_COOLOFF_TIME = timedelta(hours=1)
AXES_RESET_ON_SUCCESS = True
AXES_HTTP_RESPONSE_CODE = 429
AXES_IPWARE_META_PRECEDENCE_ORDER = [
    "HTTP_X_FORWARDED_FOR",
    "HTTP_X_REAL_IP",
    "REMOTE_ADDR",
]

# CACHES = {
#     'default': {
#         'BACKEND': 'django_redis.cache.RedisCache',
#         'LOCATION': 'redis://localhost:6379/1',  # Используем другое хранилище (DB 1) для кэша
#         'OPTIONS': {
#             'CLIENT_CLASS': 'django_redis.client.DefaultClient',
#         },
#         'TIMEOUT': 300,  # Время хранения данных в секундах (например, 5 минут)
#     }
# }

LOGGING_CONFIG = "logging.config.dictConfig"
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {
        "console": {"class": "logging.StreamHandler"},
        "my_log_file": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": BASE_DIR / "logs" / "my_log_file.log",
            "when": "midnight",  # каждый день новый файл
            "backupCount": 10,  # сколько старых файлов хранить
            "encoding": "utf-8",
            "delay": True,
        },
        "my_info_file": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": BASE_DIR / "logs" / "my_info_file.log",
            "when": "midnight",
            "backupCount": 10,
            "encoding": "utf-8",
            "delay": True,
        },
        "my_import_csv_file": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": BASE_DIR / "logs" / "my_import_csv_file.log",
            "when": "midnight",
            "backupCount": 10,
            "encoding": "utf-8",
            "delay": True,
        },
        "my_mqtt_file": {
            "level": "DEBUG",
            "class": "logging.handlers.TimedRotatingFileHandler",
            "filename": BASE_DIR / "logs" / "my_mqtt_file.log",
            "when": "midnight",
            "backupCount": 10,
            "encoding": "utf-8",
            "delay": True,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "WARNING",
        },
        "my_log": {
            "handlers": ["my_log_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "my_info": {
            "handlers": ["my_info_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "my_import_csv": {
            "handlers": ["my_import_csv_file"],
            "level": "DEBUG",
            "propagate": False,
        },
        "my_mqtt": {
            "handlers": ["my_mqtt_file"],
            "level": "DEBUG",
            "propagate": False,
        },
    },
}

# Хранилище результатов выполнения задач (опционально)
# CELERY_RESULT_BACKEND = "redis://localhost:6379/0"
# Сериализация задач и результатов
CELERY_BROKER_URL = f"{REDIS_URL}/0"
CELERY_TASK_SERIALIZER = "json"
CELERY_RESULT_SERIALIZER = "json"
CELERY_ACCEPT_CONTENT = ["json"]
CELERY_RESULT_BACKEND = "django-db"
CELERY_RESULT_EXTENDED = (
    True  # Расширяет сохранение данных, включая task_name и task_args
)
CELERY_TASK_TRACK_STARTED = True  # Отслеживает статус задачи как STARTED
CELERY_TASK_ACKS_LATE = (
    True  # Задача будет помечена как выполненная только после завершения
)
CELERY_TASK_REJECT_ON_WORKER_LOST = True  # Повтор задач, если воркер потерян
CELERY_TASK_DEFAULT_RETRY_DELAY = 20  # Задержка перед ретраем
CELERY_TASK_MAX_RETRIES = 50  # Максимальное количество ретраев
CELERY_TASK_ANNOTATIONS = {"push_update_exc_contact": {"rate_limit": "10/s"}}
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
# CELERY_TASK_TIME_LIMIT = 43200  # 12 часов
# # Дополнительно можно установить "мягкое" ограничение времени выполнения
# # Если задача превышает этот лимит, она получит предупреждение
# CELERY_TASK_SOFT_TIME_LIMIT = 43000  # Чуть меньше жёсткого лимита


MEDIA_ROOT = BASE_DIR / "uploaded_documents"
MEDIA_URL = "/uploaded_documents/"

# EAV2 Settings
EAV2_PRIMARY_KEY_FIELD = "django.db.models.IntegerField"
