# Generated by Django 5.2.5 on 2025-12-22 23:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(help_text='Unique identifier for this template', max_length=200, unique=True)),
                ('version', models.PositiveIntegerField(default=1, help_text='Template version number')),
                ('enabled', models.BooleanField(default=True, help_text='Whether this template is active')),
                ('root_model_label', models.CharField(help_text="Dotted path to root model (e.g. 'company.Employee')", max_length=200)),
                ('template_file', models.FileField(help_text='The fillable PDF template file', upload_to='pdf_plugin/templates/')),
                ('output_filename_pattern', models.CharField(default='{template.name}_{root.pk}_{now:%Y%m%d_%H%M%S}.pdf', help_text='Python format string for output filename. Available: template, root, now', max_length=255)),
                ('flatten', models.BooleanField(default=False, help_text='Best-effort: makes the result uneditable by removing form fields after filling.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PDF Template',
                'verbose_name_plural': 'PDF Templates',
                'ordering': ('name', 'version'),
                'unique_together': {('name', 'version')},
            },
        ),
        migrations.CreateModel(
            name='PDFRenderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(blank=True, max_length=200)),
                ('template_version', models.PositiveIntegerField(default=0)),
                ('root_model_label', models.CharField(max_length=200)),
                ('root_pk', models.CharField(max_length=64)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pdf_plugin.pdftemplate')),
            ],
            options={
                'verbose_name': 'PDF Render Log',
                'verbose_name_plural': 'PDF Render Logs',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='PDFFieldMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('pdf_field_name', models.CharField(help_text='Exact name of the PDF AcroForm field', max_length=200)),
                ('value_path', models.CharField(blank=True, help_text="Dotted path to value (e.g. 'company.name' or 'first_name')", max_length=500)),
                ('default_value', models.CharField(blank=True, help_text='Default value if value_path is empty or fails', max_length=500)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_maps', to='pdf_plugin.pdftemplate')),
            ],
            options={
                'verbose_name': 'PDF Field Mapping',
                'verbose_name_plural': 'PDF Field Mappings',
                'ordering': ('template', 'order', 'pdf_field_name'),
            },
        ),
    ]
