# Generated by Django 5.2.5 on 2025-12-25 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdf_plugin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdftemplate',
            name='flatten',
            field=models.BooleanField(default=False, help_text='WARNING: Flatten may remove visual appearance of filled values. Currently, flatten is disabled as it requires explicit appearance stream generation. Keep this unchecked to preserve filled form fields.'),
        ),
    ]
