# Generated by Django 5.2.5 on 2025-12-18 00:51

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the automation', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this automation')),
                ('trigger_model', models.CharField(help_text='Model path like "employees.Employee" or "company.Employees"', max_length=100)),
                ('trigger_field', models.CharField(blank=True, help_text="Field name to monitor (e.g., 'birthday', 'status')", max_length=100)),
                ('trigger_type', models.CharField(choices=[('field_changed', 'Field Changed'), ('created', 'Created'), ('deleted', 'Deleted')], help_text='Type of trigger event', max_length=20)),
                ('action_type', models.CharField(choices=[('code', 'Execute Python Code'), ('webhook', 'POST to Webhook URL')], help_text='Type of action to execute', max_length=20)),
                ('action_code', models.TextField(blank=True, help_text='Python code to execute when automation is triggered')),
                ('webhook_url', models.URLField(blank=True, help_text='Webhook URL for POST requests', validators=[django.core.validators.URLValidator()])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Automation',
                'verbose_name_plural': 'Automations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(help_text='Whether the automation executed successfully')),
                ('error_message', models.TextField(blank=True, help_text='Error message if execution failed')),
                ('object_id', models.IntegerField(help_text='ID of the object that triggered the automation')),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automations.automation')),
            ],
            options={
                'verbose_name': 'Automation Log',
                'verbose_name_plural': 'Automation Logs',
                'ordering': ['-executed_at'],
            },
        ),
    ]
