# Generated by Django 5.2.5 on 2025-12-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automationlog',
            name='model_label',
            field=models.CharField(default='', help_text='Which model triggered this automation', max_length=100),
        ),
        migrations.AlterField(
            model_name='automation',
            name='action_code',
            field=models.TextField(blank=True, help_text='Python code with access to: instance, old_value, new_value, date, datetime, models'),
        ),
        migrations.AlterField(
            model_name='automation',
            name='trigger_field',
            field=models.CharField(blank=True, help_text='Enter exact field name from the model', max_length=100),
        ),
        migrations.AlterField(
            model_name='automation',
            name='trigger_model',
            field=models.CharField(help_text="Enter as 'app_label.ModelName' (e.g., 'contacts.Contact')", max_length=100),
        ),
    ]
