# Generated by Django 5.2.5 on 2025-12-20 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0002_automationlog_model_label_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='automation',
            name='trigger_model',
            field=models.CharField(help_text="Enter as 'app_label.ModelName' (e.g., 'company.Employees', 'company.Company', 'dispatch.Dispatch')", max_length=100),
        ),
    ]
