# Generated by Django 6.0.1 on 2026-01-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='employee_record',
            field=models.FileField(blank=True, help_text='Uploaded or generated employee record PDF for the company.', null=True, upload_to='companies/employee_records/'),
        ),
    ]
