# Generated by Django 6.0.1 on 2026-01-27 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0002_company_employee_record'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employee_record',
        ),
        migrations.AddField(
            model_name='company',
            name='company_contract',
            field=models.FileField(blank=True, help_text='Uploaded or generated company contract PDF.', null=True, upload_to='companies/contracts/'),
        ),
    ]
