# Generated by Django 6.0.1 on 2026-01-27 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_remove_company_employee_record_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='company',
            name='text',
            field=models.TextField(blank=True),
        ),
    ]
