# Generated by Django 6.0.1 on 2026-02-04 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghlauth',
            name='location_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
