# Generated by Django 6.0.1 on 2026-02-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0002_ghlauth_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ghlauth',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
