# Generated by Django 5.1.7 on 2025-07-28 02:09

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('availability_status', models.CharField(blank=True, choices=[('Available', 'Available'), ('Done For Season', 'Done For Season'), ('D Rated', 'D Rated'), ('Injured', 'Injured'), ('Left Early', 'Left Early'), ('Needs Review', 'Needs Review'), ('No Response', 'No Response'), ('Not Currently Available', 'Not Currently Available'), ('Not Eligible To Work', 'Not Eligible To Work'), ('Not Interested', 'Not Interested'), ('Not Working This Year', 'Not Working This Year'), ('Priority', 'Priority'), ('Transfer', 'Transfer')], default=None, max_length=50, null=True)),
                ('date_of_change', models.DateField(blank=True, null=True)),
                ('date_of_expected_future_change', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('travel_time', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('location_state', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Location, State')),
                ('location_city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Current Location, City')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Availability',
                'verbose_name_plural': 'Availability',
            },
        ),
        migrations.CreateModel(
            name='CompanyManifest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Manifest',
                'verbose_name_plural': 'Manifests',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('inperson_required', models.BooleanField(default=False)),
                ('governing_body', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Course',
                'verbose_name_plural': 'Courses',
            },
        ),
        migrations.CreateModel(
            name='Crew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('crew_name', models.CharField(blank=True, max_length=255, null=True)),
                ('c_number', models.CharField(blank=True, max_length=100, null=True)),
                ('contract', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Crew',
                'verbose_name_plural': 'Crews',
            },
        ),
        migrations.CreateModel(
            name='CurrentAssigned',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Current Assigned',
                'verbose_name_plural': 'Current Assigned',
            },
        ),
        migrations.CreateModel(
            name='DispatchingStatus',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('time', models.CharField(blank=True, max_length=50, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('positive_interaction', models.BooleanField(default=False)),
                ('dispatch_status', models.CharField(blank=True, choices=[('ACCEPTED_DISPATCH', 'Accepted Dispatch'), ('ARRIVED', 'Arrived'), ('AVAILABLE_FOR_DISPATCH', 'Available for Dispatch'), ('CANCELED_DISPATCH', 'Canceled Dispatch'), ('CHECKED_IN', 'Checked in'), ('DENIED_DISPATCH', 'Denied Dispatch'), ('IN_ROUTE', 'In Route'), ('LEAVING_EARLY_IN_ROUTE', 'Leaving Early In Route'), ('LEFT_EARLY', 'Left Early'), ('MISSED_DISPATCH_CALL', 'Missed Dispatch Call'), ('NEEDS_REVIEW', 'Needs Review'), ('NOT_ELIGIBLE', 'Not Eligible'), ('NOT_ON_FIRE', 'Not On Fire'), ('NOT_WORKING_THIS_SEASON', 'Not Working This Season'), ('ON_FIRE', 'On Fire'), ('RESTING', 'Resting'), ('RNR', 'RnR'), ('TRANSFERRED_OUT', 'Transferred Out')], default=None, max_length=50, null=True)),
                ('dispatch_category', models.CharField(blank=True, max_length=50, null=True)),
                ('ETA', models.DateTimeField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Dispatching status',
                'verbose_name_plural': 'Dispatching statuses',
            },
        ),
        migrations.CreateModel(
            name='Draws',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(blank=True, choices=[('Cash', 'Cash'), ('Wire', 'Wire'), ('Check', 'Check'), ('Cash App', 'Cash App'), ('Other', 'Other'), ('QR Cash', 'QR Cash'), ('Zelle', 'Zelle')], max_length=50, null=True)),
                ('amount', models.CharField(blank=True, max_length=50, null=True)),
                ('signature', models.CharField(blank=True, max_length=50, null=True)),
                ('payer', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Draws',
                'verbose_name_plural': 'Draws',
            },
        ),
        migrations.CreateModel(
            name='DrugTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('result', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Drug Test',
                'verbose_name_plural': 'Drug Tests',
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, choices=[('ADDRESS', 'Address'), ('CELL_PHONE', 'Cell Phone'), ('CITY_STATE', 'City, State'), ('COMPANY_ADDRESS', 'Company Address'), ('COMPANY_NAME', 'Company Name'), ('EMAIL', 'Email Address'), ('FULL_NAME', 'Full Name'), ('PHONE_HOME', 'Phone Home'), ('PHONE_WORK', 'Phone Work'), ('RELATIONSHIP', 'Relationship')], default=None, max_length=50, null=True)),
                ('relation_to_you', models.CharField(blank=True, max_length=255, null=True)),
                ('is_primary', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Emergency Contact',
                'verbose_name_plural': 'Emergency Contacts',
            },
        ),
        migrations.CreateModel(
            name='Employee_Change_Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_value', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('new_value_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.SmallIntegerField(choices=[(0, 'New'), (19, 'Canceled'), (5, 'Completed'), (1, 'In Progress'), (400, 'Error')], default=0)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Change Queue',
                'verbose_name_plural': 'Change Queue',
            },
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('type', models.CharField(blank=True, choices=[('CREW_BOSS', 'Crew Boss'), ('INSTRUCTOR', 'Instructor'), ('NORMAL', 'Normal'), ('SQUAD_BOSS', 'Squad Boss')], max_length=50, null=True)),
                ('contact_id', models.CharField(max_length=255)),
                ('last_modified_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_modified_time', models.DateTimeField()),
                ('datetime_created', models.DateTimeField(blank=True, null=True)),
                ('status_code', models.SmallIntegerField(choices=[(0, 'New'), (19, 'Canceled'), (5, 'Completed'), (1, 'In Progress'), (400, 'Error')], default=0)),
                ('test', models.SmallIntegerField(default=0)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('job_title', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_manifested', models.BooleanField(default=False)),
                ('document', models.ImageField(blank=True, null=True, upload_to=core.utils.model_directory_path_ava, verbose_name='Photo')),
                ('document_modified_time', models.DateTimeField(blank=True, null=True)),
                ('created_in_exchange', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
        ),
        migrations.CreateModel(
            name='Employees_Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, db_index=True, max_length=512, null=True)),
                ('value_date', models.DateTimeField(blank=True, null=True)),
                ('value_file', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path_property)),
                ('value_bool', models.BooleanField(default=False)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('sync_updated_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Parameters',
                'verbose_name_plural': 'Parameters',
            },
        ),
        migrations.CreateModel(
            name='Employees_Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo_exchange', models.ImageField(blank=True, null=True, upload_to=core.utils.model_directory_path_photo, verbose_name='Photo exc')),
                ('photo_privser_cropped_picture_for_red_card', models.ImageField(blank=True, null=True, upload_to=core.utils.model_directory_path_photo, verbose_name='Photo priv cropped picture for red card')),
                ('photo_privser_passport_picture', models.ImageField(blank=True, null=True, upload_to=core.utils.model_directory_path_photo, verbose_name='Photo priv passport')),
                ('photo_privser_picture_at_field_training', models.ImageField(blank=True, null=True, upload_to=core.utils.model_directory_path_photo, verbose_name='Photo priv picture at field training')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.CreateModel(
            name='EmploymentPacket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('packet_name', models.CharField(blank=True, max_length=255, null=True)),
                ('date_sent', models.DateField(blank=True, null=True)),
                ('date_signed', models.DateField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Employment Packet',
                'verbose_name_plural': 'Employment Packets',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rated_by', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('hotline', models.CharField(blank=True, choices=[('BLANK', 'Blank'), ('HOTLINE', 'Hotline'), ('LINE_CONSTRUCTION', 'Line Construction'), ('NA', 'N/A')], default=None, max_length=50, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Evaluation',
                'verbose_name_plural': 'Evaluations',
            },
        ),
        migrations.CreateModel(
            name='Fire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fire_number', models.CharField(blank=True, max_length=100, null=True)),
                ('incident_name', models.CharField(blank=True, max_length=100, null=True)),
                ('incident_type', models.CharField(blank=True, max_length=50, null=True)),
                ('agency', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=25, null=True)),
                ('reliability_leaving', models.IntegerField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Fire',
                'verbose_name_plural': 'Fires',
            },
        ),
        migrations.CreateModel(
            name='FireCrew',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('visible', models.BooleanField(default=True)),
                ('group', models.CharField(blank=True, max_length=50, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'FireCrew',
                'verbose_name_plural': 'FireCrews',
            },
        ),
        migrations.CreateModel(
            name='FireCrewHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('added', 'Added'), ('removed', 'Removed')], max_length=10)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Crew History',
                'verbose_name_plural': 'Crew History',
            },
        ),
        migrations.CreateModel(
            name='FireRun',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firefighter_name', models.CharField(blank=True, max_length=255, null=True)),
                ('CRWB_potential', models.CharField(blank=True, max_length=255, null=True)),
                ('rating', models.CharField(blank=True, max_length=10, null=True, verbose_name='Rating')),
                ('ranking', models.CharField(blank=True, max_length=10, null=True, verbose_name='Ranking')),
                ('professionalism_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('attitude_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('sawyer_rating', models.CharField(blank=True, max_length=10, null=True)),
                ('month_year', models.CharField(blank=True, max_length=255, null=True)),
                ('hotline_shifts', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hotline shifts')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Incident date')),
                ('job_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Job title')),
                ('total_shift_tickets', models.IntegerField(blank=True, null=True, verbose_name='Total shift tickets')),
                ('operational_periods', models.IntegerField(blank=True, null=True, verbose_name='Operational periods')),
                ('activity_code', models.CharField(blank=True, max_length=25, null=True, verbose_name='Activity code')),
                ('fuel_type', models.CharField(blank=True, max_length=25, null=True, verbose_name='Fuel type')),
                ('fire_size', models.CharField(blank=True, max_length=10, null=True, verbose_name='Fire size')),
                ('eval_hotline', models.CharField(blank=True, max_length=10, null=True, verbose_name='Eval hotline')),
                ('hotline_in_remarks', models.CharField(blank=True, max_length=10, null=True, verbose_name='Hotline in remarks')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Fire Run',
                'verbose_name_plural': 'Fire Run',
            },
        ),
        migrations.CreateModel(
            name='IdentificationDocuments',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('DL', "Driver's License"), ('MEDICAL_CARD', 'Medical Card'), ('PASSPORT', 'Passport'), ('SSN', 'SSN')], max_length=50)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('number', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path)),
                ('endorsement', models.CharField(blank=True, max_length=255, null=True)),
                ('restriction', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Identification Document',
                'verbose_name_plural': 'Identification Documents',
            },
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_interaction', models.CharField(blank=True, choices=[('Called Answered', 'Called Answered'), ('Called No Answer', 'Called No Answer'), ('Called In', 'Called In'), ('Email Received', 'Email Received'), ('Email Sent', 'Email Sent'), ('Received Text', 'Received Text'), ('Sent Text', 'Sent Text'), ('WhatsApp Received', 'WhatsApp Received'), ('WhatsApp Sent', 'WhatsApp Sent'), ('Practice Dispatch Confirmed', 'Practice Dispatch Confirmed')], default=None, max_length=50, null=True)),
                ('date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('negative_interaction', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Interaction',
                'verbose_name_plural': 'Interactions',
            },
        ),
        migrations.CreateModel(
            name='IQCCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('pack_test', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path)),
                ('date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'IQC Card',
                'verbose_name_plural': 'IQC Cards',
            },
        ),
        migrations.CreateModel(
            name='MSPA',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('MSPA_number', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'MSPA',
                'verbose_name_plural': 'MSPA',
            },
        ),
        migrations.CreateModel(
            name='NomexCheckIn',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('pants_serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('shirt_serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Nomex CheckIn',
                'verbose_name_plural': 'Nomex CheckIn',
            },
        ),
        migrations.CreateModel(
            name='NomexCheckOut',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('pants_serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('shirt_serial_number', models.CharField(blank=True, max_length=255, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Nomex CheckOut',
                'verbose_name_plural': 'Nomex CheckOut',
            },
        ),
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Note',
                'verbose_name_plural': 'Notes',
            },
        ),
        migrations.CreateModel(
            name='RateOfPay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('base_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bonus_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('office_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('year', models.CharField(blank=True, max_length=50, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Rate Of Pay',
                'verbose_name_plural': 'Rate Of Pay',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_score', models.IntegerField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='TaskBook',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type_of_taskbook', models.CharField(blank=True, choices=[('CRWB', 'CRWB'), ('ENGG', 'ENGG'), ('FFT1', 'FFT1'), ('ICT5', 'ICT5'), ('SAWYER', 'Sawyer')], default=None, max_length=50, null=True)),
                ('initiated_date', models.DateField(blank=True, null=True)),
                ('completed_date', models.DateField(blank=True, null=True)),
                ('updated_date', models.DateField(blank=True, null=True)),
                ('final_evaluator', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'TaskBook',
                'verbose_name_plural': 'TaskBooks',
            },
        ),
        migrations.CreateModel(
            name='TrainingClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test_score', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Class',
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='TrainingType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, unique=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Class type',
                'verbose_name_plural': 'Class type',
            },
        ),
        migrations.CreateModel(
            name='CrewTimeReport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('document', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path)),
                ('hotline_in_remarks', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('crew', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crew_time_report_entries', to='company.crew')),
            ],
            options={
                'verbose_name': 'Crew Time Report',
                'verbose_name_plural': 'Crew Time Reports',
            },
        ),
        migrations.CreateModel(
            name='DayOnFire',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(blank=True, choices=[('CRWB', 'CRWB'), ('CRWBT', 'CRWBT'), ('ENGB', 'ENGB'), ('ENGBT', 'ENGBT'), ('FFT1', 'FFT1'), ('FFT1T', 'FFT1T'), ('FFT2', 'FFT2'), ('REP', 'REP')], default=None, max_length=50, null=True)),
                ('clockin1', models.DateTimeField(blank=True, null=True)),
                ('clockout1', models.DateTimeField(blank=True, null=True)),
                ('clockin2', models.DateTimeField(blank=True, null=True)),
                ('clockout2', models.DateTimeField(blank=True, null=True)),
                ('hours_per_day', models.IntegerField(blank=True, null=True)),
                ('document', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('crew_time_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_on_fire_entries', to='company.crewtimereport')),
            ],
            options={
                'verbose_name': 'Day On Fire',
                'verbose_name_plural': 'Days On Fire',
            },
        ),
    ]
