# Generated by Django 5.1.7 on 2025-07-28 02:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
        ('exchange', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee_change_queue',
            name='contacts_prop',
            field=models.ForeignKey(db_column='contacts_prop_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='change_queue_entries', to='exchange.contacts_prop'),
        ),
        migrations.AddField(
            model_name='employee_change_queue',
            name='employee',
            field=models.ForeignKey(db_column='employees_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='change_queue_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='emergencycontact',
            name='relationship',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact_entries_as_relationship', to='company.employees'),
        ),
        migrations.AddField(
            model_name='drugtest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drug_test_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='draws',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='dispatchingstatus',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispatching_status_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='currentassigned',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_assigned_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='crew',
            name='crew_boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crew_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='companymanifest',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_manifest_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='availability',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='employees_parameters',
            name='contacts_prop',
            field=models.ForeignKey(db_column='contacts_prop_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='contacts_prop_entries', to='exchange.contacts_prop'),
        ),
        migrations.AddField(
            model_name='employees_parameters',
            name='employee',
            field=models.ForeignKey(db_column='employees_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='employees_parameters_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='employees_pictures',
            name='employee',
            field=models.ForeignKey(db_column='employees_id', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='employees_pictures_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='employmentpacket',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employment_packet_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='evaluation_entries', to='company.crew'),
        ),
        migrations.AddField(
            model_name='crew',
            name='fire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='crew_entries', to='company.fire'),
        ),
        migrations.AddField(
            model_name='firecrew',
            name='crew_boss',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firecrew_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='employees',
            name='fire_crew',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='company.firecrew'),
        ),
        migrations.AddField(
            model_name='firecrewhistory',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firecrew_history_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='firecrewhistory',
            name='firecrew',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firecrew_history_entries', to='company.firecrew'),
        ),
        migrations.AddField(
            model_name='firerun',
            name='crew',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fire_run_entries', to='company.crew'),
        ),
        migrations.AddField(
            model_name='firerun',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fire_run_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='dayonfire',
            name='fire_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='day_on_fire_entries', to='company.firerun'),
        ),
        migrations.AddField(
            model_name='identificationdocuments',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identification_documents_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interaction_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='iqccard',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='IQC_card_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='mspa',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mspa_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='nomexcheckin',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomex_checkin_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='nomexcheckout',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nomex_checkout_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='notes',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='rateofpay',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_of_pay_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='student',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='taskbook',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_book_entries', to='company.employees'),
        ),
        migrations.AddField(
            model_name='trainingclass',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_class_entries', to='company.course'),
        ),
        migrations.AddField(
            model_name='trainingclass',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_class_entries_as_instructor', to='company.employees'),
        ),
        migrations.AddField(
            model_name='student',
            name='training_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_entries', to='company.trainingclass'),
        ),
        migrations.AddField(
            model_name='course',
            name='training_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_type_entries', to='company.trainingtype'),
        ),
        migrations.AddIndex(
            model_name='drugtest',
            index=models.Index(fields=['employee', 'updated_at'], name='company_dru_employe_2f5288_idx'),
        ),
        migrations.AddIndex(
            model_name='dispatchingstatus',
            index=models.Index(fields=['employee', 'updated_at'], name='company_dis_employe_3cc1d2_idx'),
        ),
        migrations.AddIndex(
            model_name='currentassigned',
            index=models.Index(fields=['employee', 'updated_at'], name='company_cur_employe_abf3c6_idx'),
        ),
        migrations.AddIndex(
            model_name='companymanifest',
            index=models.Index(fields=['employee', 'updated_at'], name='company_com_employe_4b4409_idx'),
        ),
        migrations.AddIndex(
            model_name='availability',
            index=models.Index(fields=['employee', 'updated_at'], name='company_ava_employe_9ca17b_idx'),
        ),
        migrations.AddIndex(
            model_name='employees_parameters',
            index=models.Index(fields=['employee', 'contacts_prop', 'updated_at'], name='company_emp_employe_353008_idx'),
        ),
        migrations.AddConstraint(
            model_name='employees_parameters',
            constraint=models.UniqueConstraint(fields=('employee', 'contacts_prop'), name='unique_employee_param'),
        ),
        migrations.AddIndex(
            model_name='employmentpacket',
            index=models.Index(fields=['employee', 'updated_at'], name='company_emp_employe_e93cdc_idx'),
        ),
        migrations.AddConstraint(
            model_name='crew',
            constraint=models.UniqueConstraint(fields=('fire', 'c_number'), name='unique_fire_c_number'),
        ),
        migrations.AddIndex(
            model_name='firecrew',
            index=models.Index(fields=['visible', 'group'], name='company_fir_visible_3bd7b4_idx'),
        ),
        migrations.AddIndex(
            model_name='employees',
            index=models.Index(fields=['is_manifested'], name='company_emp_is_mani_e25564_idx'),
        ),
        migrations.AddIndex(
            model_name='employees',
            index=models.Index(fields=['fire_crew'], name='company_emp_fire_cr_b51690_idx'),
        ),
        migrations.AddIndex(
            model_name='firerun',
            index=models.Index(fields=['employee', 'updated_at'], name='company_fir_employe_937b83_idx'),
        ),
        migrations.AddIndex(
            model_name='identificationdocuments',
            index=models.Index(fields=['employee', 'updated_at'], name='company_ide_employe_59c182_idx'),
        ),
        migrations.AddIndex(
            model_name='interaction',
            index=models.Index(fields=['employee', 'updated_at'], name='company_int_employe_a97609_idx'),
        ),
        migrations.AddIndex(
            model_name='iqccard',
            index=models.Index(fields=['employee', 'updated_at'], name='company_iqc_employe_076f5c_idx'),
        ),
        migrations.AddIndex(
            model_name='mspa',
            index=models.Index(fields=['employee', 'updated_at'], name='company_msp_employe_fd1e2c_idx'),
        ),
        migrations.AddIndex(
            model_name='nomexcheckin',
            index=models.Index(fields=['employee', 'updated_at'], name='company_nom_employe_99905f_idx'),
        ),
        migrations.AddIndex(
            model_name='nomexcheckout',
            index=models.Index(fields=['employee', 'updated_at'], name='company_nom_employe_4a4bf6_idx'),
        ),
        migrations.AddIndex(
            model_name='notes',
            index=models.Index(fields=['employee', 'updated_at'], name='company_not_employe_119743_idx'),
        ),
        migrations.AddIndex(
            model_name='rateofpay',
            index=models.Index(fields=['employee', 'updated_at'], name='company_rat_employe_179d50_idx'),
        ),
        migrations.AddIndex(
            model_name='taskbook',
            index=models.Index(fields=['employee', 'updated_at'], name='company_tas_employe_085720_idx'),
        ),
        migrations.AddConstraint(
            model_name='trainingclass',
            constraint=models.UniqueConstraint(fields=('course', 'date'), name='unique_course_date'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['employee', 'updated_at'], name='company_stu_employe_d56c33_idx'),
        ),
    ]
