# Generated by Django 5.1.7 on 2025-07-28 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crew',
            options={'verbose_name': 'Crew Fire Run', 'verbose_name_plural': 'Crews Fire Run'},
        ),
    ]
