# Generated by Django 5.1.7 on 2025-08-02 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_crew_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='phone',
        ),
    ]
