# Generated by Django 5.1.7 on 2025-08-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_remove_employees_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayonfire',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
