# Generated by Django 5.1.7 on 2025-08-03 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_dayonfire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayonfire',
            name='hours_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
