# Generated by Django 5.1.7 on 2025-08-05 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_alter_dayonfire_hours_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayonfire',
            name='hotline_in_remarks',
            field=models.BooleanField(default=False, verbose_name='Hotline in remarks'),
        ),
        migrations.AddField(
            model_name='dayonfire',
            name='operational_periods',
            field=models.BooleanField(default=False, verbose_name='Operational periods'),
        ),
        migrations.AlterField(
            model_name='firerun',
            name='job_title',
            field=models.CharField(blank=True, choices=[('CRWB', 'CRWB'), ('CRWBT', 'CRWBT'), ('ENGB', 'ENGB'), ('ENGBT', 'ENGBT'), ('FFT1', 'FFT1'), ('FFT1T', 'FFT1T'), ('FFT2', 'FFT2'), ('REP', 'REP')], default=None, max_length=50, null=True),
        ),
    ]
