# Generated by Django 5.1.7 on 2025-08-06 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0007_dayonfire_hotline_in_remarks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='firerun',
            name='hotline_in_remarks_bool',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hotline in remarks (bool)'),
        ),
    ]
