# Generated by Django 5.1.7 on 2025-08-06 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_firerun_hotline_in_remarks_bool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='firerun',
            name='hotline_in_remarks',
        ),
    ]
