# Generated by Django 5.1.7 on 2025-08-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_remove_firerun_hotline_in_remarks'),
    ]

    operations = [
        migrations.RenameField(
            model_name='firerun',
            old_name='hotline_in_remarks_bool',
            new_name='hotline_in_remarks',
        ),
    ]
