# Generated by Django 5.1.7 on 2025-08-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0010_rename_hotline_in_remarks_bool_firerun_hotline_in_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firerun',
            name='hotline_in_remarks',
            field=models.BooleanField(blank=True, null=True, verbose_name='Hotline in remarks'),
        ),
    ]
