# Generated by Django 5.1.7 on 2025-08-06 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0011_alter_firerun_hotline_in_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayonfire',
            name='crew_time_report',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='day_on_fire_entries', to='company.crewtimereport'),
        ),
    ]
