# Generated by Django 5.1.7 on 2025-08-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0012_alter_dayonfire_crew_time_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='fire',
            name='activity_code',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Activity code'),
        ),
        migrations.AddField(
            model_name='fire',
            name='fire_size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Fire size'),
        ),
        migrations.AddField(
            model_name='fire',
            name='fuel_type',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Fuel type'),
        ),
        migrations.AlterField(
            model_name='dayonfire',
            name='job_title',
            field=models.CharField(blank=True, choices=[('FFT1T', 'FFT1T'), ('FFT1', 'FFT1'), ('FFT2', 'FFT2'), ('CRWBT', 'CRWBT'), ('CRWB', 'CRWB'), ('ENGBT', 'ENGBT'), ('ENGB', 'ENGB'), ('REP', 'REP')], default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='firerun',
            name='job_title',
            field=models.CharField(blank=True, choices=[('FFT1T', 'FFT1T'), ('FFT1', 'FFT1'), ('FFT2', 'FFT2'), ('CRWBT', 'CRWBT'), ('CRWB', 'CRWB'), ('ENGBT', 'ENGBT'), ('ENGB', 'ENGB'), ('REP', 'REP')], default=None, max_length=50, null=True),
        ),
    ]
