# Generated by Django 5.1.7 on 2025-08-12 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0013_fire_activity_code_fire_fire_size_fire_fuel_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fire',
            name='incident_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='fire',
            constraint=models.UniqueConstraint(fields=('fire_number', 'incident_name'), name='uniq_fire_num_name'),
        ),
    ]
