# Generated by Django 5.1.7 on 2025-08-12 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0014_alter_fire_incident_name_fire_uniq_fire_num_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fire',
            name='incident_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddConstraint(
            model_name='firerun',
            constraint=models.UniqueConstraint(fields=('crew', 'employee', 'job_title'), name='unique_crew_employee_jt'),
        ),
    ]
