# Generated by Django 5.1.7 on 2025-08-12 03:21

import django.db.models.functions.comparison
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0015_alter_fire_incident_name_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='fire',
            name='uniq_fire_num_name',
        ),
        migrations.AlterField(
            model_name='crew',
            name='c_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='fire',
            constraint=models.UniqueConstraint(django.db.models.functions.comparison.Coalesce('fire_number', models.Value('-')), django.db.models.functions.comparison.Coalesce('incident_name', models.Value('-')), name='uniq_fire_num_name_null_token'),
        ),
    ]
