# Generated by Django 5.1.7 on 2025-08-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_remove_fire_uniq_fire_num_name_alter_crew_c_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mspa',
            name='pending',
            field=models.DateField(blank=True, null=True),
        ),
    ]
