# Generated by Django 5.1.7 on 2025-08-15 23:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_mspa_pending'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
