# Generated by Django 5.2.5 on 2025-08-17 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0019_firerun_created_at'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                UPDATE company_firerun
                SET hotline_shifts = NULL
                WHERE hotline_shifts IS NOT NULL
                  AND (TRIM(hotline_shifts) = "" OR hotline_shifts REGEXP "[^0-9]");
                """,
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.AlterField(
            model_name='firerun',
            name='hotline_shifts',
            field=models.IntegerField(blank=True, null=True, verbose_name='Hotline shifts'),
        ),
    ]
