# Generated by Django 5.2.5 on 2025-08-21 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0020_alter_firerun_hotline_shifts'),
    ]

    operations = [
        migrations.AddField(
            model_name='firerun',
            name='crwb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fire_run_entries_as_crwb', to='company.employees'),
        ),
    ]
