# Generated by Django 5.2.5 on 2025-08-22 01:40

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_firerun_crwb'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='i9',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='I-9'),
        ),
    ]
