# Generated by Django 5.2.5 on 2025-08-22 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_employees_i9'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='i9',
        ),
    ]
