# Generated by Django 5.2.5 on 2025-09-04 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0024_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('address', models.CharField(blank=True, max_length=512, null=True, verbose_name='Address')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone')),
                ('dot', models.CharField(blank=True, max_length=100, null=True, verbose_name='DOT')),
                ('tax', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tax ID')),
                ('mspa', models.CharField(blank=True, max_length=100, null=True, verbose_name='MSPA')),
                ('email', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
            },
        ),
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
