# Generated by Django 5.2.5 on 2025-09-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0025_company_delete_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='location_city',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Current Location, City'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='location_state',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='Current Location, State'),
        ),
        migrations.AlterField(
            model_name='availability',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='dispatchingstatus',
            name='dispatch_category',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='dispatchingstatus',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dispatchingstatus',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
    ]
