# Generated by Django 5.2.5 on 2025-09-18 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0027_employees_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingclass',
            name='association',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Association'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='type',
            field=models.CharField(blank=True, choices=[('CREW_BOSS', 'Crew Boss'), ('INSTRUCTOR', 'Instructor'), ('NORMAL', 'Normal'), ('SQUAD_BOSS', 'Squad Boss'), ('CREW_REP', 'Crew Rep')], max_length=50, null=True),
        ),
    ]
