# Generated by Django 5.2.5 on 2025-09-22 17:33

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_trainingclass_association_alter_employees_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='verified',
            field=models.DateField(blank=True, null=True, verbose_name='Verified'),
        ),
        migrations.AlterField(
            model_name='student',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='student',
            name='test_score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Test score'),
        ),
        migrations.AlterField(
            model_name='student',
            name='training_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_entries', to='company.trainingclass', verbose_name='Class'),
        ),
    ]
