# Generated by Django 5.2.5 on 2025-10-09 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0029_student_verified_alter_student_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='training_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_type_entries', to='company.trainingtype', unique=True),
        ),
    ]
