# Generated by Django 5.2.5 on 2025-10-09 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0030_alter_course_training_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='type',
            field=models.CharField(blank=True, choices=[('CREW_BOSS', 'Crew Boss'), ('ENGINE_BOSS', 'Engine Boss'), ('INSTRUCTOR', 'Instructor'), ('NORMAL', 'Normal'), ('SQUAD_BOSS', 'Squad Boss'), ('CREW_REP', 'Crew Rep')], max_length=50, null=True),
        ),
    ]
