# Generated by Django 5.2.5 on 2025-10-10 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0031_alter_employees_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='certificate_confirmed',
            field=models.DateField(blank=True, null=True, verbose_name='Certificate confirmed'),
        ),
    ]
