# Generated by Django 5.2.5 on 2025-10-11 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0032_student_certificate_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='training_type',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='training_type_entries', to='company.trainingtype'),
        ),
    ]
