# Generated by Django 5.2.5 on 2025-10-14 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0033_alter_course_training_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='employees',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tags_employees', to='company.tag'),
        ),
    ]
