# Generated by Django 5.2.5 on 2025-10-14 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0034_tag_employees_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
