# Generated by Django 5.2.5 on 2025-10-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0035_alter_tag_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees_parameters',
            name='value_array',
            field=models.JSONField(default=list),
        ),
    ]
