# Generated by Django 5.2.5 on 2025-11-06 23:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0036_employees_parameters_value_array'),
        ('dispatch', '0018_contracts_per_dof_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='crew',
            name='dispatch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_entries', to='dispatch.dispatch'),
        ),
        migrations.AlterField(
            model_name='crew',
            name='fire',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crew_entries', to='company.fire'),
        ),
    ]
