# Generated by Django 5.2.5 on 2025-11-07 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0037_crew_dispatch_alter_crew_fire'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crew',
            options={'verbose_name': 'Crew (history)', 'verbose_name_plural': 'Crews (history)'},
        ),
    ]
