# Generated by Django 5.2.5 on 2025-11-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0038_alter_crew_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskbook',
            name='type_of_taskbook',
            field=models.CharField(blank=True, choices=[('CRWB', 'CRWB'), ('ENGB', 'ENGB'), ('FFT1', 'FFT1'), ('ICT5', 'ICT5'), ('SAWYER', 'Sawyer')], default=None, max_length=50, null=True),
        ),
    ]
