# Generated by Django 5.2.5 on 2025-12-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0039_alter_taskbook_type_of_taskbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firerun',
            name='operational_periods',
            field=models.IntegerField(blank=True, null=True, verbose_name='Oper. periods'),
        ),
    ]
