# Generated by Django 5.2.5 on 2025-12-03 01:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0040_alter_firerun_operational_periods'),
    ]

    operations = [
        migrations.AddField(
            model_name='firerun',
            name='task_book',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fire_run_entries', to='company.taskbook'),
        ),
    ]
