# Generated by Django 5.2.5 on 2025-12-03 23:41

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0041_firerun_task_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='articles_of_organization_file',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='Articles of Organization'),
        ),
        migrations.AddField(
            model_name='company',
            name='mspa_license_file',
            field=models.ImageField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='MSPA License'),
        ),
    ]
