# Generated by Django 5.2.5 on 2025-12-06 22:41

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0042_company_articles_of_organization_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverLicense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='State, Number')),
                ('endorsement', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endorsements')),
                ('restriction', models.CharField(blank=True, max_length=255, null=True, verbose_name='Restrictions')),
                ('front_of_id', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='Front of ID')),
                ('back_of_id', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='Back of ID')),
                ('id_2_front', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='ID 2 Front')),
                ('id_2_back', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='ID 2 Back')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dl_documents_entries', to='company.employees')),
            ],
            options={
                'verbose_name': 'Driver License',
                'verbose_name_plural': 'Driver License',
                'indexes': [models.Index(fields=['employee', 'updated_at'], name='company_dri_employe_7925a3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='Issue Date')),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('type', models.CharField(choices=[('DOL', 'DOL'), ('DOT', 'DOT')], default='', max_length=50)),
                ('document', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_card_entries', to='company.employees')),
            ],
            options={
                'verbose_name': 'Medical Card',
                'verbose_name_plural': 'Medical Card',
                'indexes': [models.Index(fields=['employee', 'updated_at'], name='company_med_employe_590bd3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Number')),
                ('document', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_entries', to='company.employees')),
            ],
            options={
                'verbose_name': 'Passport',
                'verbose_name_plural': 'Passport',
                'indexes': [models.Index(fields=['employee', 'updated_at'], name='company_pas_employe_666965_idx')],
            },
        ),
        migrations.CreateModel(
            name='SocialSecurityNumber',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expiration_date', models.DateField(blank=True, null=True, verbose_name='Expiration Date')),
                ('number', models.CharField(blank=True, max_length=255, null=True, verbose_name='Number')),
                ('document', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('modified_by', models.CharField(blank=True, max_length=100, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssn_entries', to='company.employees')),
            ],
            options={
                'verbose_name': 'Passport',
                'verbose_name_plural': 'Passport',
                'indexes': [models.Index(fields=['employee', 'updated_at'], name='company_soc_employe_af8f95_idx')],
            },
        ),
    ]
