# Generated by Django 5.2.5 on 2025-12-06 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0043_driverlicense_medicalcard_passport_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialsecuritynumber',
            options={'verbose_name': 'Social Security Number', 'verbose_name_plural': 'Social Security Number'},
        ),
    ]
