# Generated by Django 5.2.5 on 2025-12-07 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0044_alter_socialsecuritynumber_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='Issue Date'),
        ),
        migrations.AlterField(
            model_name='medicalcard',
            name='type',
            field=models.CharField(blank=True, choices=[('DOL', 'DOL'), ('DOT', 'DOT')], default='', max_length=50, null=True),
        ),
    ]
