# Generated by Django 5.2.5 on 2025-12-07 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0045_passport_issue_date_alter_medicalcard_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalcard',
            name='type',
            field=models.CharField(blank=True, choices=[('DOL', 'DOL'), ('DOT', 'DOT')], default='', help_text='Type of medical card', max_length=50, null=True, verbose_name='Type'),
        ),
    ]
