# Generated by Django 5.2.5 on 2025-12-10 23:43

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0046_alter_medicalcard_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('datetime', models.DateTimeField(blank=True, null=True, verbose_name='Datetime')),
                ('bank_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Bank #')),
                ('bank_name', models.CharField(blank=True, choices=[('Chase Bank', 'Chase Bank'), ('Columbia Bank', 'Columbia Bank'), ('American Express', 'American Express')], max_length=100, null=True, verbose_name='Bank Name')),
                ('account_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Account Number')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Amount')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Type')),
                ('category', models.CharField(blank=True, max_length=100, null=True, verbose_name='Category')),
                ('project_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Project Code')),
                ('fixed_variable', models.BooleanField(default=False, verbose_name='Fixed/Variable')),
                ('required_discretionary', models.BooleanField(default=False, verbose_name='Required/Discretionary')),
                ('approved', models.BooleanField(default=False, verbose_name='Approved')),
                ('growth', models.BooleanField(default=False, verbose_name='Growth')),
                ('file', models.FileField(blank=True, null=True, upload_to=core.utils.model_directory_path, verbose_name='File')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Bank Transaction',
                'verbose_name_plural': 'Bank Transactions',
                'ordering': ('-datetime', '-updated_at'),
                'indexes': [models.Index(fields=['datetime', 'bank_name'], name='company_ban_datetim_f16e2c_idx'), models.Index(fields=['user', 'datetime'], name='company_ban_user_id_d3efda_idx')],
            },
        ),
    ]
