# Generated by Django 6.0.1 on 2026-04-01 15:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0009_alter_contact_privser_contact_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='IDScanGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(max_length=140, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('grayscale_enabled', models.BooleanField(default=True)),
                ('upscale_enabled', models.BooleanField(default=True)),
                ('deskew_enabled', models.BooleanField(default=True)),
                ('binarize_enabled', models.BooleanField(default=True)),
                ('noise_removal_enabled', models.BooleanField(default=True)),
                ('isolate_roi_enabled', models.BooleanField(default=True)),
                ('optimize_ocr_enabled', models.BooleanField(default=True)),
                ('apply_psm_enabled', models.BooleanField(default=True)),
                ('apply_whitelist_enabled', models.BooleanField(default=True)),
                ('post_process_enabled', models.BooleanField(default=True)),
                ('data_validation_enabled', models.BooleanField(default=True)),
                ('remove_background_enabled', models.BooleanField(default=True)),
                ('level_perspective_enabled', models.BooleanField(default=True)),
                ('scale_factor', models.DecimalField(decimal_places=2, default=1.75, max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('default_psm', models.PositiveSmallIntegerField(default=6)),
                ('default_whitelist', models.CharField(blank=True, max_length=255)),
                ('threshold_mode', models.CharField(choices=[('adaptive', 'Adaptive'), ('otsu', 'Otsu')], default='adaptive', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'ID scan group',
                'verbose_name_plural': 'ID scan groups',
                'ordering': ['name', 'id'],
            },
        ),
        migrations.CreateModel(
            name='IDScanTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=140)),
                ('document_type', models.CharField(choices=[('driver_license', 'Driver license'), ('state_id', 'State ID'), ('permit', 'Permit'), ('passport', 'Passport'), ('other', 'Other')], default='driver_license', max_length=30)),
                ('issuer_region', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('target_width', models.PositiveIntegerField(default=1000)),
                ('target_height', models.PositiveIntegerField(default=630)),
                ('accepted_date_input_formats', models.CharField(default='%m/%d/%Y,%m-%d-%Y,%m %d %Y,%m%d%Y', help_text='Comma-separated Python strptime formats for DOB/expiry normalization.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='id_scanner.idscangroup')),
            ],
            options={
                'verbose_name': 'ID scan template',
                'verbose_name_plural': 'ID scan templates',
                'ordering': ['group__name', 'name', 'id'],
                'unique_together': {('group', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='IDScanRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_image', models.ImageField(upload_to='id_scanner/source/')),
                ('warped_image', models.ImageField(blank=True, upload_to='id_scanner/warped/')),
                ('processed_image', models.ImageField(blank=True, upload_to='id_scanner/processed/')),
                ('raw_ocr_text', models.JSONField(blank=True, default=dict)),
                ('extracted_data', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('error', 'Error')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('confidence_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='id_scan_records', to='contacts.contact')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_records', to='id_scanner.idscangroup')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_records', to='id_scanner.idscantemplate')),
            ],
            options={
                'verbose_name': 'ID scan record',
                'verbose_name_plural': 'ID scan records',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='IDScanField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField()),
                ('label', models.CharField(max_length=120)),
                ('field_type', models.CharField(choices=[('full_name', 'Full name'), ('dob', 'Date of birth'), ('id_number', 'ID number'), ('expiry', 'Expiry'), ('address', 'Address'), ('custom', 'Custom')], default='custom', max_length=20)),
                ('roi_left', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('roi_top', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('roi_width', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(1)])),
                ('roi_height', models.DecimalField(decimal_places=4, max_digits=5, validators=[django.core.validators.MinValueValidator(0.0001), django.core.validators.MaxValueValidator(1)])),
                ('psm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('whitelist', models.CharField(blank=True, max_length=255)),
                ('validation_regex', models.CharField(blank=True, max_length=255)),
                ('expected_length', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('required', models.BooleanField(default=False)),
                ('normalize_whitespace', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='id_scanner.idscantemplate')),
            ],
            options={
                'verbose_name': 'ID scan field',
                'verbose_name_plural': 'ID scan fields',
                'ordering': ['order', 'id'],
                'unique_together': {('template', 'key')},
            },
        ),
    ]
