# Generated by Django 5.2.5 on 2025-09-20 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0028_trainingclass_association_alter_employees_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyWorkers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('worker_id', models.CharField(db_index=True, max_length=128, unique=True, verbose_name='Worker Id')),
                ('employee_id', models.CharField(db_index=True, max_length=128, verbose_name='Employee Id')),
                ('worker_type', models.CharField(max_length=50, verbose_name='Worker Type')),
                ('exemption_type', models.CharField(max_length=50, verbose_name='Exemption Type')),
                ('work_state', models.CharField(max_length=10, verbose_name='State')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='BirthDate')),
                ('sex', models.CharField(max_length=50, verbose_name='Sex')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='Hire Date')),
                ('family_name', models.CharField(max_length=100, verbose_name='FamilyName')),
                ('middle_name', models.CharField(max_length=100, verbose_name='MiddleName')),
                ('given_name', models.CharField(max_length=100, verbose_name='GivenName')),
                ('legal_id_type', models.CharField(max_length=50, verbose_name='Legal Id Type')),
                ('legal_id_value', models.CharField(max_length=50, verbose_name='Legal Id Value')),
                ('labor_assignment_id', models.CharField(max_length=50, verbose_name='Labor Assignment Id')),
                ('location_id', models.CharField(max_length=50, verbose_name='Location Id')),
                ('organization_id', models.CharField(max_length=50, verbose_name='Organization id')),
                ('organization_name', models.CharField(max_length=128, verbose_name='oRganization name')),
                ('organization_number', models.CharField(max_length=50, verbose_name='Organization number')),
                ('worker_status_id', models.CharField(max_length=50, verbose_name='Worker Status Id')),
                ('status_type', models.CharField(max_length=50, verbose_name='Status Type')),
                ('status_reason', models.CharField(max_length=50, verbose_name='Status Reason')),
                ('status_effective_date', models.DateField(blank=True, null=True, verbose_name='Status Effective Date')),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employees', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_workers_as_employees', to='company.employees')),
            ],
            options={
                'verbose_name': 'Company Worker',
                'verbose_name_plural': 'Company Workers',
                'indexes': [models.Index(fields=['worker_id'], name='paychex_com_worker__91b7b4_idx'), models.Index(fields=['employee_id'], name='paychex_com_employe_546336_idx')],
            },
        ),
    ]
