# Generated by Django 5.2.5 on 2025-09-20 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paychex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyworkers',
            name='exemption_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Exemption Type'),
        ),
        migrations.AlterField(
            model_name='companyworkers',
            name='family_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='FamilyName'),
        ),
        migrations.AlterField(
            model_name='companyworkers',
            name='given_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='GivenName'),
        ),
        migrations.AlterField(
            model_name='companyworkers',
            name='labor_assignment_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Labor Assignment Id'),
        ),
        migrations.AlterField(
            model_name='companyworkers',
            name='legal_id_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Legal Id Type'),
        ),
        migrations.AlterField(
            model_name='companyworkers',
            name='legal_id_value',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Legal Id Value'),
        ),
        migrations.AlterField(
            model_name='companyworkers',
            name='location_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Location Id'),
        ),
        migrations.AlterField(
            model_name='companyworkers',
            name='middle_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='MiddleName'),
        ),
        migrations.AlterField(
            model_name='companyworkers',
            name='organization_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization id'),
        ),
        migrations.AlterField(
            model_name='companyworkers',
            name='organization_name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='oRganization name'),
        ),
        migrations.AlterField(
            model_name='companyworkers',
            name='organization_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Organization number'),
        ),
        migrations.AlterField(
            model_name='companyworkers',
            name='sex',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sex'),
        ),
        migrations.AlterField(
            model_name='companyworkers',
            name='status_reason',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Reason'),
        ),
        migrations.AlterField(
            model_name='companyworkers',
            name='status_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Status Type'),
        ),
        migrations.AlterField(
            model_name='companyworkers',
            name='work_state',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='companyworkers',
            name='worker_status_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Worker Status Id'),
        ),
        migrations.AlterField(
            model_name='companyworkers',
            name='worker_type',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Worker Type'),
        ),
    ]
