# Generated by Django 5.2.5 on 2025-09-20 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paychex', '0002_alter_companyworkers_exemption_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyworkers',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Employee Id'),
        ),
    ]
