# Generated by Django 5.2.5 on 2025-09-21 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paychex', '0003_alter_companyworkers_employee_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayPeriod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.CharField(blank=True, max_length=64, null=True)),
                ('payperiod_id', models.CharField(db_index=True, max_length=64, unique=True)),
                ('interval_code', models.CharField(blank=True, max_length=64, null=True)),
                ('status', models.CharField(blank=True, max_length=64, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('submit_by_date', models.DateField(blank=True, null=True)),
                ('check_date', models.DateField(blank=True, null=True)),
                ('check_count', models.IntegerField(blank=True, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'PayPeriod',
                'verbose_name_plural': 'PayPeriods',
                'ordering': ('-start_date',),
                'indexes': [models.Index(fields=['company_id', 'start_date'], name='paychex_pay_company_9041db_idx'), models.Index(fields=['payperiod_id'], name='paychex_pay_payperi_b07fea_idx')],
            },
        ),
    ]
