# Generated by Django 5.2.5 on 2025-09-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paychex', '0004_payperiod'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyworkers',
            name='company_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
