# Generated by Django 5.2.5 on 2025-09-21 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paychex', '0005_companyworkers_company_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paycheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paycheck_id', models.CharField(db_index=True, max_length=128, unique=True)),
                ('company_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('payperiod_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('worker_id', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('check_date', models.DateField(blank=True, null=True)),
                ('gross', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('net', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paychex_worker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='paychex.companyworkers')),
            ],
        ),
        migrations.CreateModel(
            name='PaycheckComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('component_type', models.CharField(blank=True, max_length=64, null=True)),
                ('raw_json', models.JSONField(blank=True, null=True)),
                ('paycheck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='paychex.paycheck')),
            ],
        ),
    ]
