# Generated by Django 5.2.5 on 2025-09-22 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paychex', '0006_paycheck_paycheckcomponent'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheck',
            name='check_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paycheck',
            name='check_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paycheckcomponent',
            name='check_component_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paycheckcomponent',
            name='classification_type',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paycheckcomponent',
            name='component_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paycheckcomponent',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='paycheckcomponent',
            name='labor_assignment_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paycheckcomponent',
            name='organization_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='paycheckcomponent',
            name='organization_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='paycheckcomponent',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='check_date',
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='gross',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='paycheck',
            name='net',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='paycheckcomponent',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='paycheckcomponent',
            name='component_type',
            field=models.CharField(blank=True, choices=[('EARNING', 'Earning'), ('DEDUCTION', 'Deduction'), ('TAX', 'Tax'), ('OTHER', 'Other')], max_length=32, null=True),
        ),
        migrations.AddIndex(
            model_name='paycheck',
            index=models.Index(fields=['company_id'], name='paychex_pay_company_b40a05_idx'),
        ),
        migrations.AddIndex(
            model_name='paycheck',
            index=models.Index(fields=['payperiod_id'], name='paychex_pay_payperi_a2e235_idx'),
        ),
        migrations.AddIndex(
            model_name='paycheck',
            index=models.Index(fields=['worker_id'], name='paychex_pay_worker__3496fd_idx'),
        ),
        migrations.AddIndex(
            model_name='paycheck',
            index=models.Index(fields=['check_date'], name='paychex_pay_check_d_595d81_idx'),
        ),
        migrations.AddIndex(
            model_name='paycheckcomponent',
            index=models.Index(fields=['component_id'], name='paychex_pay_compone_74fcfd_idx'),
        ),
        migrations.AddIndex(
            model_name='paycheckcomponent',
            index=models.Index(fields=['check_component_id'], name='paychex_pay_check_c_084915_idx'),
        ),
        migrations.AddIndex(
            model_name='paycheckcomponent',
            index=models.Index(fields=['component_type'], name='paychex_pay_compone_3f385c_idx'),
        ),
    ]
