# Generated by Django 5.2.5 on 2025-09-22 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('paychex', '0007_paycheck_check_number_paycheck_check_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paycheck',
            old_name='imported_at',
            new_name='created_at',
        ),
    ]
