# Generated by Django 5.2.5 on 2025-10-29 16:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paychex', '0008_rename_imported_at_paycheck_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='paycheckcomponent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paycheckcomponent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
