# Generated by Django 5.2.5 on 2025-11-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('paychex', '0009_paycheckcomponent_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimePunch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_identifier', models.CharField(db_index=True, max_length=64, verbose_name='EmpIdentifier')),
                ('external_id', models.CharField(max_length=128, verbose_name='External ID')),
                ('first_name', models.CharField(blank=True, max_length=200, null=True)),
                ('last_name', models.CharField(blank=True, max_length=200, null=True)),
                ('apply_to_date', models.DateField(blank=True, null=True, verbose_name='ApplyToDate')),
                ('in_time', models.DateTimeField(blank=True, null=True, verbose_name='InTime')),
                ('in_time_actual', models.DateTimeField(blank=True, null=True, verbose_name='InTimeActual')),
                ('out_time', models.DateTimeField(blank=True, null=True, verbose_name='OutTime')),
                ('out_time_actual', models.DateTimeField(blank=True, null=True, verbose_name='OutTimeActual')),
                ('in_time_slice_preid', models.IntegerField(blank=True, null=True, verbose_name='InTimeSlicePreID')),
                ('out_time_slice_preid', models.IntegerField(blank=True, null=True, verbose_name='OutTimeSlicePreID')),
                ('in_latitude', models.FloatField(blank=True, null=True, verbose_name='InLatitude')),
                ('in_longitude', models.FloatField(blank=True, null=True, verbose_name='InLongitude')),
                ('out_latitude', models.FloatField(blank=True, null=True, verbose_name='OutLatitude')),
                ('out_longitude', models.FloatField(blank=True, null=True, verbose_name='OutLongitude')),
                ('in_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='InType')),
                ('out_type', models.CharField(blank=True, max_length=64, null=True, verbose_name='OutType')),
                ('pay_type_id', models.IntegerField(blank=True, null=True, verbose_name='PayTypeID')),
                ('pay_type_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='PayTypeName')),
                ('pay_type_code', models.CharField(blank=True, max_length=64, null=True, verbose_name='PayTypeCode')),
                ('regular_minutes', models.IntegerField(blank=True, null=True, verbose_name='RegularMinutes')),
                ('unpaid_minutes', models.IntegerField(blank=True, null=True, verbose_name='UnpaidMinutes')),
                ('ot_info', models.JSONField(blank=True, default=list, verbose_name='OTInfo')),
                ('labor_levels', models.JSONField(blank=True, default=dict, verbose_name='LaborLevels')),
                ('in_clock_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='InClockID')),
                ('out_clock_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='OutClockID')),
                ('export_code', models.CharField(blank=True, max_length=255, null=True)),
                ('raw', models.JSONField(blank=True, null=True, verbose_name='RawResponse')),
                ('row_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Time Punch',
                'verbose_name_plural': 'Time Punches',
                'ordering': ('-in_time',),
                'indexes': [models.Index(fields=['emp_identifier', 'apply_to_date'], name='paychex_tim_emp_ide_d089ce_idx')],
                'unique_together': {('emp_identifier', 'external_id')},
            },
        ),
    ]
