# Generated by Django 5.2.5 on 2025-10-18 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch_event',
            name='event_type',
            field=models.CharField(choices=[('CLOCK_IN', 'Clock In'), ('CLOCK_OUT', 'Clock Out')], db_index=True, max_length=32),
        ),
    ]
