# Generated by Django 5.2.5 on 2025-10-18 01:10

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_punch_event_event_type'),
        ('company', '0036_employees_parameters_value_array'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='punch_event',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterModelOptions(
            name='work_session',
            options={'ordering': ['-start_time']},
        ),
        migrations.AddField(
            model_name='punch_event',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='punch_events', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='work_session',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_sessions', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='punch_event',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.employees', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='punch_event',
            name='timestamp',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='work_session',
            name='duration_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work_session',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.employees', verbose_name='Employee'),
        ),
        migrations.AlterField(
            model_name='work_session',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='punch_event',
            index=models.Index(fields=['user', 'timestamp'], name='attendance__user_id_420b00_idx'),
        ),
        migrations.AddIndex(
            model_name='punch_event',
            index=models.Index(fields=['employee', 'timestamp'], name='attendance__employe_45b7d3_idx'),
        ),
        migrations.AddIndex(
            model_name='work_session',
            index=models.Index(fields=['user', 'start_time'], name='attendance__user_id_c0b79f_idx'),
        ),
        migrations.AddIndex(
            model_name='work_session',
            index=models.Index(fields=['employee', 'start_time'], name='attendance__employe_13a328_idx'),
        ),
    ]
