# Generated by Django 5.2.5 on 2025-10-22 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_alter_punch_event_options_alter_work_session_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='punch_event',
            name='event_type',
            field=models.CharField(choices=[('Clocked In', 'Clock In'), ('Clocked Out', 'Clock Out')], db_index=True, max_length=32),
        ),
    ]
